In [2]:
import pandas as pd

# Leer datasets
df1 = pd.read_csv("../data/raw/DataScience_salaries_2024.csv")
df2 = pd.read_csv("../data/raw/ds_salaries.csv", index_col=0)
df3 = pd.read_csv("../data/raw/Latest_Data_Science_Salaries.csv")

In [3]:
df1.head()

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2021,MI,FT,Data Scientist,30400000,CLP,40038,CL,100,CL,L
1,2021,MI,FT,BI Data Analyst,11000000,HUF,36259,HU,50,US,L
2,2020,MI,FT,Data Scientist,11000000,HUF,35735,HU,50,HU,L
3,2021,MI,FT,ML Engineer,8500000,JPY,77364,JP,50,JP,S
4,2022,SE,FT,Lead Machine Learning Engineer,7500000,INR,95386,IN,50,IN,L

In [4]:
df2.head()

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2020,MI,FT,Data Scientist,70000,EUR,79833,DE,0,DE,L
1,2020,SE,FT,Machine Learning Scientist,260000,USD,260000,JP,0,JP,S
2,2020,SE,FT,Big Data Engineer,85000,GBP,109024,GB,50,GB,M
3,2020,MI,FT,Product Data Analyst,20000,USD,20000,HN,0,HN,S
4,2020,SE,FT,Machine Learning Engineer,150000,USD,150000,US,50,US,L

In [5]:
df3.head()

,Job Title,Employment Type,Experience Level,Expertise Level,Salary,Salary Currency,Company Location,Salary in USD,Employee Residence,Company Size,Year
0,Data Engineer,Full-Time,Senior,Expert,210000,United States Dollar,United States,210000,United States,Medium,2023
1,Data Engineer,Full-Time,Senior,Expert,165000,United States Dollar,United States,165000,United States,Medium,2023
2,Data Engineer,Full-Time,Senior,Expert,185900,United States Dollar,United States,185900,United States,Medium,2023
3,Data Engineer,Full-Time,Senior,Expert,129300,United States Dollar,United States,129300,United States,Medium,2023
4,Data Scientist,Full-Time,Senior,Expert,140000,United States Dollar,United States,140000,United States,Medium,2023

## Creación de la variable `remote_ratio` para la concatenación de datasets

Antes de combinar los distintos datasets fue necesario asegurar que todos compartieran la misma estructura de columnas. Uno de los datasets originales no incluía la variable `remote_ratio`, lo que impedía realizar la concatenación directa.

Para resolver este problema, se creó la columna `remote_ratio` en los datasets donde no existía, inicializándola con valores nulos. De esta forma se pudo garantizar la compatibilidad entre las estructuras de los dataframes y realizar la concatenación correctamente.

La gestión de los valores faltantes de esta variable se abordará posteriormente durante la fase de limpieza de datos.

In [6]:
# ---- LIMPIEZA BÁSICA DF3 (solo para igualar estructura) ----

df3 = df3.rename(columns={
    "Year": "work_year",
    "Job Title": "job_title",
    "Experience Level": "experience_level",
    "Employment Type": "employment_type",
    "Salary": "salary",
    "Salary Currency": "salary_currency",
    "Salary in USD": "salary_in_usd",
    "Employee Residence": "employee_residence",
    "Company Location": "company_location",
    "Company Size": "company_size"
})

# eliminar columna que no existe en los otros
df3 = df3.drop(columns=["Expertise Level"], errors="ignore")


# ---- HOMOGENEIZAR ESTRUCTURA ----

dfs = [df1, df2, df3]

for df in dfs:

    # crear columna remote_ratio si no existe
    if "remote_ratio" not in df.columns:
        df["remote_ratio"] = None

# ---- UNIR DATASETS ----

df_all = pd.concat(dfs, ignore_index=True)


print("Shape dataset combinado:", df_all.shape)
df_all.head()

Shape dataset combinado: (18745, 11)

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2021,MI,FT,Data Scientist,30400000,CLP,40038,CL,100,CL,L
1,2021,MI,FT,BI Data Analyst,11000000,HUF,36259,HU,50,US,L
2,2020,MI,FT,Data Scientist,11000000,HUF,35735,HU,50,HU,L
3,2021,MI,FT,ML Engineer,8500000,JPY,77364,JP,50,JP,S
4,2022,SE,FT,Lead Machine Learning Engineer,7500000,INR,95386,IN,50,IN,L

In [10]:
df_all.to_csv("../data/raw/salaries_concat.csv", index=False)