In [50]:
import pandas as pd

# Leer datasets
df1 = pd.read_csv("DataScience_salaries_2024.csv")
df2 = pd.read_csv("ds_salaries.csv", index_col=0)
df3 = pd.read_csv("Latest_Data_Science_Salaries.csv")

In [51]:
df1.head()

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2021,MI,FT,Data Scientist,30400000,CLP,40038,CL,100,CL,L
1,2021,MI,FT,BI Data Analyst,11000000,HUF,36259,HU,50,US,L
2,2020,MI,FT,Data Scientist,11000000,HUF,35735,HU,50,HU,L
3,2021,MI,FT,ML Engineer,8500000,JPY,77364,JP,50,JP,S
4,2022,SE,FT,Lead Machine Learning Engineer,7500000,INR,95386,IN,50,IN,L

In [52]:
df2.head()

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2020,MI,FT,Data Scientist,70000,EUR,79833,DE,0,DE,L
1,2020,SE,FT,Machine Learning Scientist,260000,USD,260000,JP,0,JP,S
2,2020,SE,FT,Big Data Engineer,85000,GBP,109024,GB,50,GB,M
3,2020,MI,FT,Product Data Analyst,20000,USD,20000,HN,0,HN,S
4,2020,SE,FT,Machine Learning Engineer,150000,USD,150000,US,50,US,L

In [53]:
df3.head()

,Job Title,Employment Type,Experience Level,Expertise Level,Salary,Salary Currency,Company Location,Salary in USD,Employee Residence,Company Size,Year
0,Data Engineer,Full-Time,Senior,Expert,210000,United States Dollar,United States,210000,United States,Medium,2023
1,Data Engineer,Full-Time,Senior,Expert,165000,United States Dollar,United States,165000,United States,Medium,2023
2,Data Engineer,Full-Time,Senior,Expert,185900,United States Dollar,United States,185900,United States,Medium,2023
3,Data Engineer,Full-Time,Senior,Expert,129300,United States Dollar,United States,129300,United States,Medium,2023
4,Data Scientist,Full-Time,Senior,Expert,140000,United States Dollar,United States,140000,United States,Medium,2023

## Creación de la variable `remote_ratio` para la concatenación de datasets

Antes de combinar los distintos datasets fue necesario asegurar que todos compartieran la misma estructura de columnas. Uno de los datasets originales no incluía la variable `remote_ratio`, lo que impedía realizar la concatenación directa.

Para resolver este problema, se creó la columna `remote_ratio` en los datasets donde no existía, inicializándola con valores nulos. De esta forma se pudo garantizar la compatibilidad entre las estructuras de los dataframes y realizar la concatenación correctamente.

La gestión de los valores faltantes de esta variable se abordará posteriormente durante la fase de limpieza de datos.

In [ ]:
# ---- LIMPIEZA BÁSICA DF3 (solo para igualar estructura) ----

df3 = df3.rename(columns={
    "Year": "work_year",
    "Job Title": "job_title",
    "Experience Level": "experience_level",
    "Employment Type": "employment_type",
    "Salary": "salary",
    "Salary Currency": "salary_currency",
    "Salary in USD": "salary_in_usd",
    "Employee Residence": "employee_residence",
    "Company Location": "company_location",
    "Company Size": "company_size"
})

# eliminar columna que no existe en los otros
df3 = df3.drop(columns=["Expertise Level"], errors="ignore")


# ---- HOMOGENEIZAR ESTRUCTURA ----

dfs = [df1, df2, df3]

for df in dfs:

    # crear columna remote_ratio si no existe
    if "remote_ratio" not in df.columns:
        df["remote_ratio"] = None

# ---- UNIR DATASETS ----

df_all = pd.concat(dfs, ignore_index=True)


print("Shape dataset combinado:", df_all.shape)
df_all.head()

Shape dataset combinado: (18745, 11)

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2021,MI,FT,Data Scientist,30400000,CLP,40038,CL,100,CL,L
1,2021,MI,FT,BI Data Analyst,11000000,HUF,36259,HU,50,US,L
2,2020,MI,FT,Data Scientist,11000000,HUF,35735,HU,50,HU,L
3,2021,MI,FT,ML Engineer,8500000,JPY,77364,JP,50,JP,S
4,2022,SE,FT,Lead Machine Learning Engineer,7500000,INR,95386,IN,50,IN,L

In [55]:
def eda_basico(df):

    print("\n🔍 PRIMER VISTAZO A LOS DATOS")

    print("\n📌 Primeras filas")
    display(df.head())

    print("\n📌 Últimas filas")
    display(df.tail())

    print("\n📌 Muestra aleatoria")
    display(df.sample(5))


    print("\n🧱 ESTRUCTURA DEL DATAFRAME")

    print(f"\n📐 Dimensiones: {df.shape}")

    print("\n📋 Columnas")
    display(df.columns)

    print("\n🧠 Información general")
    df.info()

    print("\n📊 Tipos de datos")
    display(df.dtypes)


    print("\n📉 ESTADÍSTICAS DESCRIPTIVAS")

    print("\n📈 Variables numéricas")
    display(df.describe().T)

    print("\n🔤 Variables categóricas")
    display(df.describe(include='O').T)


    print("\n🔢 CARDINALIDAD")

    print("\nValores únicos por columna")
    display(df.nunique())


    print("\n🚫 VALORES NULOS")

    print("\nConteo de nulos")
    display(df.isnull().sum())

    print("\nPorcentaje de nulos (%)")
    display(((df.isnull().sum()/len(df))*100).round(2))


    print("\n📎 DUPLICADOS")

    dup = df.duplicated().sum()
    print(f"\nDuplicados: {dup}")

    if dup > 0:
        display(df[df.duplicated()])


    print("\n📊 VALUE COUNTS (categóricas)")

    cat_cols = df.select_dtypes(include="object").columns

    for col in cat_cols:
        print(f"\n📌 {col}")
        display(df[col].value_counts())


    # =========================
    # EXTRA PARA TU DATASET
    # =========================

    print("\n💰 SALARIO MEDIO POR JOB TITLE")

    display(
        df.groupby("job_title")["salary_in_usd"]
        .mean()
        .sort_values(ascending=False)
        .head(15)
    )


    print("\n🚨 DETECCIÓN DE OUTLIERS EN SALARIO (IQR)")

    Q1 = df["salary_in_usd"].quantile(0.25)
    Q3 = df["salary_in_usd"].quantile(0.75)

    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = df[(df["salary_in_usd"] < lower) | (df["salary_in_usd"] > upper)]

    print(f"Outliers detectados: {len(outliers)}")

    display(outliers.head())

In [56]:
eda_basico(df_all)

🔍 PRIMER VISTAZO A LOS DATOS

📌 Primeras filas

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2021,MI,FT,Data Scientist,30400000,CLP,40038,CL,100,CL,L
1,2021,MI,FT,BI Data Analyst,11000000,HUF,36259,HU,50,US,L
2,2020,MI,FT,Data Scientist,11000000,HUF,35735,HU,50,HU,L
3,2021,MI,FT,ML Engineer,8500000,JPY,77364,JP,50,JP,S
4,2022,SE,FT,Lead Machine Learning Engineer,7500000,INR,95386,IN,50,IN,L

📌 Últimas filas

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
18740,2020,Senior,Full-Time,Data Scientist,412000,United States Dollar,412000,United States,None,United States,Large
18741,2021,Mid,Full-Time,Principal Data Scientist,151000,United States Dollar,151000,United States,None,United States,Large
18742,2020,Entry,Full-Time,Data Scientist,105000,United States Dollar,105000,United States,None,United States,Small
18743,2020,Entry,Contract,Business Data Analyst,100000,United States Dollar,100000,United States,None,United States,Large
18744,2021,Senior,Full-Time,Data Science Manager,7000000,Indian Rupee,94665,India,None,India,Large

📌 Muestra aleatoria

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
13894,2023,MI,FT,Machine Learning Research Engineer,60000,GBP,73824,GB,0,GB,L
2849,2022,SE,FT,Data Scientist,203500,USD,203500,US,0,US,M
17051,2023,Mid,Full-Time,Data Scientist,45000,Euro,48585,Spain,None,Spain,Medium
4204,2024,SE,FT,Machine Learning Engineer,180000,USD,180000,US,0,US,M
14004,2023,MI,FT,Data Scientist,56000,EUR,60462,DE,100,DE,L

🧱 ESTRUCTURA DEL DATAFRAME

📐 Dimensiones: (18745, 11)

📋 Columnas

Index(['work_year', 'experience_level', 'employment_type', 'job_title',
       'salary', 'salary_currency', 'salary_in_usd', 'employee_residence',
       'remote_ratio', 'company_location', 'company_size'],
      dtype='object')

🧠 Información general
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18745 entries, 0 to 18744
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   work_year           18745 non-null  int64
 1   experience_level    18745 non-null  object
 2   employment_type     18745 non-null  object
 3   job_title           18745 non-null  object
 4   salary              18745 non-null  int64
 5   salary_currency     18745 non-null  object
 6   salary_in_usd       18745 non-null  int64
 7   employee_residence  18745 non-null  object
 8   remote_ratio        15445 non-null  object
 9   company_location    18745 non-null  object
 10  company_size        18745 non-null  object
dtypes: int64(3), object(8)
memory usage: 1.6+ MB

📊 Tipos de datos

work_year              int64
experience_level      object
employment_type       object
job_title             object
salary                 int64
salary_currency       object
salary_in_usd          int64
employee_residence    object
remote_ratio          object
company_location      object
company_size          object
dtype: object

📉 ESTADÍSTICAS DESCRIPTIVAS

📈 Variables numéricas

,count,mean,std,min,25%,50%,75%,max
work_year,18745.0,2022.969485,0.797542,2020.0,2023.0,2023.0,2023.0,2024.0
salary,18745.0,177149.144092,521317.594183,4000.0,100000.0,140400.0,187259.0,30400000.0
salary_in_usd,18745.0,147288.483916,69431.460112,2859.0,100000.0,140000.0,185000.0,800000.0

🔤 Variables categóricas

                    count unique            top   freq
experience_level    18745      8             SE   9976
employment_type     18745      8             FT  15360
job_title           18745    157  Data Engineer   3996
salary_currency     18745     46            USD  14080
employee_residence  18745    171             US  13258
remote_ratio        15445      3              0   9980
company_location    18745    148             US  13330
company_size        18745      6              M  14000

🔢 CARDINALIDAD

Valores únicos por columna

work_year                5
experience_level         8
employment_type          8
job_title              157
salary                2372
salary_currency         46
salary_in_usd         2791
employee_residence     171
remote_ratio             3
company_location       148
company_size             6
dtype: int64

🚫 VALORES NULOS

Conteo de nulos

work_year                0
experience_level         0
employment_type          0
job_title                0
salary                   0
salary_currency          0
salary_in_usd            0
employee_residence       0
remote_ratio          3300
company_location         0
company_size             0
dtype: int64

Porcentaje de nulos (%)

work_year              0.0
experience_level       0.0
employment_type        0.0
job_title              0.0
salary                 0.0
salary_currency        0.0
salary_in_usd          0.0
employee_residence     0.0
remote_ratio          17.6
company_location       0.0
company_size           0.0
dtype: float64

📎 DUPLICADOS

Duplicados: 6216

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
72,2024,MI,FT,Machine Learning Scientist,750000,USD,750000,US,0,US,M
84,2024,MI,FT,Research Engineer,720000,USD,720000,US,0,US,M
93,2024,SE,FT,Machine Learning Engineer,550000,USD,550000,US,0,US,M
97,2024,SE,FT,Research Scientist,500000,USD,500000,US,100,US,M
105,2024,MI,FT,Research Engineer,440000,USD,440000,US,0,US,M
...,...,...,...,...,...,...,...,...,...,...,...
15440,2022,SE,FT,Data Engineer,154000,USD,154000,US,100,US,M
15441,2022,SE,FT,Data Engineer,126000,USD,126000,US,100,US,M
15442,2022,SE,FT,Data Analyst,129000,USD,129000,US,0,US,M
15443,2022,SE,FT,Data Analyst,150000,USD,150000,US,100,US,M
15444,2022,MI,FT,AI Scientist,200000,USD,200000,IN,100,US,L

📊 VALUE COUNTS (categóricas)

📌 experience_level

experience_level
SE           9976
MI           3766
Senior       2065
EN           1236
Mid           797
EX            467
Entry         292
Executive     146
Name: count, dtype: int64

📌 employment_type

employment_type
FT           15360
Full-Time     3261
PT              37
CT              31
FL              17
Contract        15
Part-Time       13
Freelance       11
Name: count, dtype: int64

📌 job_title

job_title
Data Engineer                    3996
Data Scientist                   3793
Data Analyst                     2745
Machine Learning Engineer        1883
Research Scientist                595
                                 ...
Applied Research Scientist          1
CRM Data Analyst                    1
Quantitative Research Analyst       1
3D Computer Vision Researcher       1
Data Engineer 2                     1
Name: count, Length: 157, dtype: int64

📌 salary_currency

salary_currency
USD                       14080
United States Dollar       2770
GBP                         611
EUR                         519
Euro                        222
British Pound Sterling      181
INR                          80
CAD                          69
Indian Rupee                 45
Canadian Dollar              29
AUD                          14
PLN                          10
Australian Dollar            10
CHF                           9
SGD                           8
JPY                           7
Polish Zloty                  6
TRY                           6
BRL                           6
Singapore Dollar              6
Swiss Franc                   5
DKK                           5
HUF                           5
Japanese Yen                  4
Hungarian Forint              3
Turkish Lira                  3
Danish Krone                  3
Brazilian Real                3
MXN                           3
THB                           2
Thai Baht                     2
CLP                           2
CNY                           2
Norwegian Krone               2
NOK                           2
HKD                           1
PHP                           1
ILS                           1
ZAR                           1
NZD                           1
Philippine Peso               1
South African Rand            1
Israeli New Shekel            1
Hong Kong Dollar              1
Mexican Peso                  1
Chilean Peso                  1
Name: count, dtype: int64

📌 employee_residence

employee_residence
US                13258
United States      2453
GB                  691
CA                  419
United Kingdom      245
                  ...
Jersey                1
Serbia                1
New Zealand           1
Luxembourg            1
Malta                 1
Name: count, Length: 171, dtype: int64

📌 remote_ratio

remote_ratio
0      9980
100    5118
50      347
Name: count, dtype: int64

📌 company_location

company_location
US                      13330
United States            2495
GB                        702
CA                        422
United Kingdom            251
                        ...
Iraq                        1
New Zealand                 1
Chile                       1
Moldova, Republic of        1
Malta                       1
Name: count, Length: 148, dtype: int64

📌 company_size

company_size
M         14000
Medium     2707
L          1181
Large       442
S           264
Small       151
Name: count, dtype: int64

💰 SALARIO MEDIO POR JOB TITLE

job_title
Analytics Engineering Manager     399880.000000
Data Science Tech Lead            375000.000000
Managing Director Data Science    286666.666667
AWS Data Architect                258000.000000
AI Architect                      252935.062500
Head of Machine Learning          250406.333333
Cloud Data Architect              250000.000000
Principal Data Engineer           230846.625000
Director of Data Science          213073.050847
Data Analytics Lead               209326.952381
Prompt Engineer                   205093.588235
Head of Data                      200192.768116
Principal Data Scientist          199749.576923
Data Infrastructure Engineer      198935.000000
Robotics Software Engineer        196625.000000
Name: salary_in_usd, dtype: float64

🚨 DETECCIÓN DE OUTLIERS EN SALARIO (IQR)
Outliers detectados: 332

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
46,2023,SE,FT,AI Scientist,1500000,ILS,417937,IL,0,IL,L
66,2024,MI,FT,AI Architect,800000,USD,800000,CA,100,CA,M
68,2024,EN,FT,Data Analyst,774000,USD,774000,MX,0,MX,M
69,2024,SE,FT,Analytics Engineer,750000,USD,750000,US,0,US,M
70,2024,MI,FT,Machine Learning Scientist,750000,USD,750000,US,0,US,M

## Resumen del Análisis Exploratorio (EDA)

Tras combinar los tres datasets originales en un único dataframe, se realizó un análisis exploratorio con el objetivo de comprender la estructura de los datos, detectar inconsistencias y definir las transformaciones necesarias antes de la fase de limpieza.

Durante la exploración se identificaron varios aspectos relevantes. En primer lugar, la variable `job_title` presenta una alta cardinalidad, con más de 150 títulos distintos que en muchos casos representan variaciones del mismo tipo de rol. Para facilitar el análisis posterior, será necesario agrupar estos títulos en categorías profesionales más amplias.

También se detectaron inconsistencias en algunas variables categóricas como `experience_level`, `employment_type` y `company_size`, donde los valores aparecían representados de distintas formas según el dataset de origen. Estas variables deberán normalizarse para asegurar coherencia en el análisis.

En las variables geográficas (`company_location` y `employee_residence`) se observaron diferencias en el formato de los países, apareciendo tanto códigos ISO como nombres completos. Estos valores se estandarizarán al formato de códigos ISO para evitar duplicidades en los análisis por país.

Además, se identificaron valores faltantes en la variable `remote_ratio`, que posteriormente deberán gestionarse para facilitar su interpretación.

Por último, al combinar los distintos datasets se detectaron **6.216 registros duplicados**, que deberán eliminarse durante la fase de limpieza para evitar distorsiones en los análisis posteriores.

Estas observaciones guían el proceso de limpieza, cuyo objetivo será obtener un dataset consistente, homogéneo y preparado para su posterior análisis y visualización en Power BI.