# **LIMPIEZA Y TRANSFORMACIÓN DE LOS DATOS**

Este notebook aplica las transformaciones de limpieza derivadas del EDA y realiza validaciones básicas para asegurar consistencia y calidad de los datos antes del análisis.

**Principios**
- Transformar y exportar el dataset limpio a `data/processed/`.
- Documentar cada transformación y su motivación.

In [144]:
import pandas as pd
import numpy as np
import regex as re
import unicodedata
import ast


pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
pd.set_option("display.width", None)

#### **1. CARGA DE LOS DATASETS**

- Importar los datasets originales que servirán como base para las fases de limpieza, corrección y transformación de los datos.
- Tras la carga, se realiza una verificación básica para confirmar la correcta lectura de los archivos, dimensiones y la estructura general.

In [145]:
path1 = "../data/raw/data_science_job_posts_2025.csv"
path2 = "../data/raw/Distribución de las ofertas de empleo tech según el tipo de profesión tecnológica.csv"
path3 = "../data/raw/empresas por tamaño que contratan empleados ICT.csv"
path4 = "../data/raw/eu_data_jobs_salaries.csv"
path5 = "../data/raw/Número o proporción de ofertas de empleo online que buscan especialistas tecnológicos (ICT).csv"
path6 = "../data/raw/porcentaje de especialistas empleados por edad.csv"
path7 = "../data/raw/porcentaje de especialistas empleados por nivel educativo.csv"
path8 = "../data/raw/porcentaje de especialistas empleados por sector.csv"
path9 = "../data/raw/porcentaje de especialistas empleados por sexo.csv"
path10 = "../data/raw/porcentaje_profesionales_tecnologia_empleo_total_europa.csv"
path11 = "../data/raw/sectores que contratan empleados ICT.csv"
df1 = pd.read_csv(path1)
df2 = pd.read_csv(path2)
df3 = pd.read_csv(path3)
df4 = pd.read_csv(path4)
df5 = pd.read_csv(path5)
df6 = pd.read_csv(path6)
df7 = pd.read_csv(path7)
df8 = pd.read_csv(path8)
df9 = pd.read_csv(path9)
df10 = pd.read_csv(path10)
df11 = pd.read_csv(path11)

In [146]:
dfs = [df1, df2, df3, df4, df5, df6, df7, df8, df9, df10, df11]

for i, df in enumerate(dfs, start=1):
    print(f"\n================ DATASET {i} ================")
    print(f"Dataset: {df.shape[0]} filas × {df.shape[1]} columnas")
    display(df.head())

================ DATASET 1 ================
Dataset: 944 filas × 13 columnas

,job_title,seniority_level,status,company,location,post_date,headquarter,industry,ownership,company_size,revenue,salary,skills
0,data scientist,senior,hybrid,company_003,"Grapevine, TX . Hybrid",17 days ago,"Bentonville, AR, US",Retail,Public,€352.44B,Public,"€100,472 - €200,938","['spark', 'r', 'python', 'scala', 'machine lea..."
1,data scientist,lead,hybrid,company_005,"Fort Worth, TX . Hybrid",15 days ago,"Detroit, MI, US",Manufacturing,Public,"155,030",€51.10B,"€118,733","['spark', 'r', 'python', 'sql', 'machine learn..."
2,data scientist,senior,on-site,company_007,"Austin, TX . Toronto, Ontario, Canada . Kirkla...",a month ago,"Redwood City, CA, US",Technology,Public,"25,930",€33.80B,"€94,987 - €159,559","['aws', 'git', 'python', 'docker', 'sql', 'mac..."
3,data scientist,senior,hybrid,company_008,"Chicago, IL . Scottsdale, AZ . Austin, TX . Hy...",8 days ago,"San Jose, CA, US",Technology,Public,"34,690",€81.71B,"€112,797 - €194,402","['sql', 'r', 'python']"
4,data scientist,NaN,on-site,company_009,On-site,3 days ago,"Stamford, CT, US",Finance,Private,"1,800",Private,"€114,172 - €228,337",[]

================ DATASET 2 ================
Dataset: 4533 filas × 19 columnas

,STRUCTURE,STRUCTURE_ID,STRUCTURE_NAME,freq,Time frequency,isco08,International Standard Classification of Occupations 2008 (ISCO-08),unit,Unit of measure,geo,Geopolitical entity (reporting),TIME_PERIOD,Time,OBS_VALUE,Observation value,OBS_FLAG,Observation status (Flag) V2 structure,CONF_STATUS,Confidentiality status (flag)
0,dataflow,ESTAT:ISOC_SK_OJA2(1.0),Distribution by occupation (ISCO-08) of the la...,Q,Quarterly,OC133,Information and communications technology serv...,PC,Percentage,AT,Austria,2019-Q4,NaN,2.5,NaN,NaN,NaN,NaN,NaN
1,dataflow,ESTAT:ISOC_SK_OJA2(1.0),Distribution by occupation (ISCO-08) of the la...,Q,Quarterly,OC133,Information and communications technology serv...,PC,Percentage,AT,Austria,2020-Q1,NaN,2.5,NaN,NaN,NaN,NaN,NaN
2,dataflow,ESTAT:ISOC_SK_OJA2(1.0),Distribution by occupation (ISCO-08) of the la...,Q,Quarterly,OC133,Information and communications technology serv...,PC,Percentage,AT,Austria,2020-Q2,NaN,2.4,NaN,NaN,NaN,NaN,NaN
3,dataflow,ESTAT:ISOC_SK_OJA2(1.0),Distribution by occupation (ISCO-08) of the la...,Q,Quarterly,OC133,Information and communications technology serv...,PC,Percentage,AT,Austria,2020-Q3,NaN,2.2,NaN,NaN,NaN,NaN,NaN
4,dataflow,ESTAT:ISOC_SK_OJA2(1.0),Distribution by occupation (ISCO-08) of the la...,Q,Quarterly,OC133,Information and communications technology serv...,PC,Percentage,AT,Austria,2020-Q4,NaN,2.2,NaN,NaN,NaN,NaN,NaN

================ DATASET 3 ================
Dataset: 3253 filas × 23 columnas

,STRUCTURE,STRUCTURE_ID,STRUCTURE_NAME,freq,Time frequency,size_emp,Size classes in number of persons employed,nace_r2,Statistical classification of economic activities in the European Community (NACE Rev. 2),indic_is,Information society indicator,unit,Unit of measure,geo,Geopolitical entity (reporting),TIME_PERIOD,Time,OBS_VALUE,Observation value,OBS_FLAG,Observation status (Flag) V2 structure,CONF_STATUS,Confidentiality status (flag)
0,dataflow,ESTAT:ISOC_SKE_ITSPE(1.0),Enterprises that employ ICT specialists by siz...,A,Annual,0-9,From 0 to 9 persons employed,C10-S951_X_K,"All activities (except agriculture, forestry a...",E_ITSP2,Enterprise employed ICT/IT specialists (reduce...,PC_ENT,Percentage of enterprises,DE,Germany,2022,NaN,6.33,NaN,NaN,NaN,NaN,NaN
1,dataflow,ESTAT:ISOC_SKE_ITSPE(1.0),Enterprises that employ ICT specialists by siz...,A,Annual,0-9,From 0 to 9 persons employed,C10-S951_X_K,"All activities (except agriculture, forestry a...",E_ITSP2,Enterprise employed ICT/IT specialists (reduce...,PC_ENT,Percentage of enterprises,DE,Germany,2024,NaN,7.10,NaN,NaN,NaN,NaN,NaN
2,dataflow,ESTAT:ISOC_SKE_ITSPE(1.0),Enterprises that employ ICT specialists by siz...,A,Annual,0-9,From 0 to 9 persons employed,C10-S951_X_K,"All activities (except agriculture, forestry a...",E_ITSP2,Enterprise employed ICT/IT specialists (reduce...,PC_ENT,Percentage of enterprises,ES,Spain,2017,NaN,3.27,NaN,NaN,NaN,NaN,NaN
3,dataflow,ESTAT:ISOC_SKE_ITSPE(1.0),Enterprises that employ ICT specialists by siz...,A,Annual,0-9,From 0 to 9 persons employed,C10-S951_X_K,"All activities (except agriculture, forestry a...",E_ITSP2,Enterprise employed ICT/IT specialists (reduce...,PC_ENT,Percentage of enterprises,ES,Spain,2018,NaN,2.89,NaN,NaN,NaN,NaN,NaN
4,dataflow,ESTAT:ISOC_SKE_ITSPE(1.0),Enterprises that employ ICT specialists by siz...,A,Annual,0-9,From 0 to 9 persons employed,C10-S951_X_K,"All activities (except agriculture, forestry a...",E_ITSP2,Enterprise employed ICT/IT specialists (reduce...,PC_ENT,Percentage of enterprises,ES,Spain,2019,NaN,2.85,NaN,NaN,NaN,NaN,NaN

================ DATASET 4 ================
Dataset: 120 filas × 5 columnas

   country currency                role  salary_min  salary_max
0  Austria      EUR        Data Analyst       35000       70000
1  Austria      EUR      Data Scientist       37000       85000
2  Austria      EUR    Business Analyst       35000       75000
3  Austria      EUR  IT Project Manager       40000       90000
4  Belgium      EUR        Data Analyst       35000       60000

================ DATASET 5 ================
Dataset: 7239 filas × 17 columnas

,STRUCTURE,STRUCTURE_ID,STRUCTURE_NAME,freq,Time frequency,unit,Unit of measure,geo,Geopolitical entity (reporting),TIME_PERIOD,Time,OBS_VALUE,Observation value,OBS_FLAG,Observation status (Flag) V2 structure,CONF_STATUS,Confidentiality status (flag)
0,dataflow,ESTAT:ISOC_SK_OJA1(1.0),Labour market demand for ICT specialists in on...,Q,Quarterly,PC,Percentage,AT,Austria,2019-Q4,NaN,11.9,NaN,NaN,NaN,NaN,NaN
1,dataflow,ESTAT:ISOC_SK_OJA1(1.0),Labour market demand for ICT specialists in on...,Q,Quarterly,PC,Percentage,AT,Austria,2020-Q1,NaN,12.0,NaN,NaN,NaN,NaN,NaN
2,dataflow,ESTAT:ISOC_SK_OJA1(1.0),Labour market demand for ICT specialists in on...,Q,Quarterly,PC,Percentage,AT,Austria,2020-Q2,NaN,12.9,NaN,NaN,NaN,NaN,NaN
3,dataflow,ESTAT:ISOC_SK_OJA1(1.0),Labour market demand for ICT specialists in on...,Q,Quarterly,PC,Percentage,AT,Austria,2020-Q3,NaN,13.6,NaN,NaN,NaN,NaN,NaN
4,dataflow,ESTAT:ISOC_SK_OJA1(1.0),Labour market demand for ICT specialists in on...,Q,Quarterly,PC,Percentage,AT,Austria,2020-Q4,NaN,14.8,NaN,NaN,NaN,NaN,NaN

================ DATASET 6 ================
Dataset: 2752 filas × 19 columnas

,STRUCTURE,STRUCTURE_ID,STRUCTURE_NAME,freq,Time frequency,unit,Unit of measure,age,Age class,geo,Geopolitical entity (reporting),TIME_PERIOD,Time,OBS_VALUE,Observation value,OBS_FLAG,Observation status (Flag) V2 structure,CONF_STATUS,Confidentiality status (flag)
0,dataflow,ESTAT:ISOC_SKS_ITSPA(1.0),Employed ICT specialists by age,A,Annual,PC,Percentage,Y15-34,From 15 to 34 years,AT,Austria,2004,NaN,48.4,NaN,be,"break in time series, estimated",NaN,NaN
1,dataflow,ESTAT:ISOC_SKS_ITSPA(1.0),Employed ICT specialists by age,A,Annual,PC,Percentage,Y15-34,From 15 to 34 years,AT,Austria,2005,NaN,49.2,NaN,be,"break in time series, estimated",NaN,NaN
2,dataflow,ESTAT:ISOC_SKS_ITSPA(1.0),Employed ICT specialists by age,A,Annual,PC,Percentage,Y15-34,From 15 to 34 years,AT,Austria,2006,NaN,48.0,NaN,e,estimated,NaN,NaN
3,dataflow,ESTAT:ISOC_SKS_ITSPA(1.0),Employed ICT specialists by age,A,Annual,PC,Percentage,Y15-34,From 15 to 34 years,AT,Austria,2007,NaN,47.3,NaN,be,"break in time series, estimated",NaN,NaN
4,dataflow,ESTAT:ISOC_SKS_ITSPA(1.0),Employed ICT specialists by age,A,Annual,PC,Percentage,Y15-34,From 15 to 34 years,AT,Austria,2008,NaN,48.5,NaN,e,estimated,NaN,NaN

================ DATASET 7 ================
Dataset: 3146 filas × 19 columnas

,STRUCTURE,STRUCTURE_ID,STRUCTURE_NAME,freq,Time frequency,unit,Unit of measure,isced11,International Standard Classification of Education (ISCED 2011),geo,Geopolitical entity (reporting),TIME_PERIOD,Time,OBS_VALUE,Observation value,OBS_FLAG,Observation status (Flag) V2 structure,CONF_STATUS,Confidentiality status (flag)
0,dataflow,ESTAT:ISOC_SKS_ITSPE(1.0),Employed ICT specialists by educational attain...,A,Annual,PC,Percentage,ED0-4,"Less than primary, primary, secondary and post...",AT,Austria,2004,NaN,63.2,NaN,be,"break in time series, estimated",NaN,NaN
1,dataflow,ESTAT:ISOC_SKS_ITSPE(1.0),Employed ICT specialists by educational attain...,A,Annual,PC,Percentage,ED0-4,"Less than primary, primary, secondary and post...",AT,Austria,2005,NaN,66.0,NaN,be,"break in time series, estimated",NaN,NaN
2,dataflow,ESTAT:ISOC_SKS_ITSPE(1.0),Employed ICT specialists by educational attain...,A,Annual,PC,Percentage,ED0-4,"Less than primary, primary, secondary and post...",AT,Austria,2006,NaN,64.9,NaN,be,"break in time series, estimated",NaN,NaN
3,dataflow,ESTAT:ISOC_SKS_ITSPE(1.0),Employed ICT specialists by educational attain...,A,Annual,PC,Percentage,ED0-4,"Less than primary, primary, secondary and post...",AT,Austria,2007,NaN,63.4,NaN,be,"break in time series, estimated",NaN,NaN
4,dataflow,ESTAT:ISOC_SKS_ITSPE(1.0),Employed ICT specialists by educational attain...,A,Annual,PC,Percentage,ED0-4,"Less than primary, primary, secondary and post...",AT,Austria,2008,NaN,67.1,NaN,e,estimated,NaN,NaN

================ DATASET 8 ================
Dataset: 40900 filas × 19 columnas

,STRUCTURE,STRUCTURE_ID,STRUCTURE_NAME,freq,Time frequency,nace_r2,Statistical classification of economic activities in the European Community (NACE Rev. 2),unit,Unit of measure,geo,Geopolitical entity (reporting),TIME_PERIOD,Time,OBS_VALUE,Observation value,OBS_FLAG,Observation status (Flag) V2 structure,CONF_STATUS,Confidentiality status (flag)
0,dataflow,ESTAT:ISOC_SKS_ITSPN2(1.0),Employed ICT specialists by NACE Rev. 2 activity,A,Annual,A,"Agriculture, forestry and fishing",PC_EMP,Percentage of total employment,AT,Austria,2008,NaN,NaN,NaN,bu,"break in time series, low reliability",NaN,NaN
1,dataflow,ESTAT:ISOC_SKS_ITSPN2(1.0),Employed ICT specialists by NACE Rev. 2 activity,A,Annual,A,"Agriculture, forestry and fishing",PC_EMP,Percentage of total employment,AT,Austria,2010,NaN,NaN,NaN,u,low reliability,NaN,NaN
2,dataflow,ESTAT:ISOC_SKS_ITSPN2(1.0),Employed ICT specialists by NACE Rev. 2 activity,A,Annual,A,"Agriculture, forestry and fishing",PC_EMP,Percentage of total employment,AT,Austria,2011,NaN,NaN,NaN,bu,"break in time series, low reliability",NaN,NaN
3,dataflow,ESTAT:ISOC_SKS_ITSPN2(1.0),Employed ICT specialists by NACE Rev. 2 activity,A,Annual,A,"Agriculture, forestry and fishing",PC_EMP,Percentage of total employment,AT,Austria,2012,NaN,NaN,NaN,u,low reliability,NaN,NaN
4,dataflow,ESTAT:ISOC_SKS_ITSPN2(1.0),Employed ICT specialists by NACE Rev. 2 activity,A,Annual,A,"Agriculture, forestry and fishing",PC_EMP,Percentage of total employment,AT,Austria,2013,NaN,NaN,NaN,u,low reliability,NaN,NaN

================ DATASET 9 ================
Dataset: 2752 filas × 19 columnas

,STRUCTURE,STRUCTURE_ID,STRUCTURE_NAME,freq,Time frequency,unit,Unit of measure,sex,Sex,geo,Geopolitical entity (reporting),TIME_PERIOD,Time,OBS_VALUE,Observation value,OBS_FLAG,Observation status (Flag) V2 structure,CONF_STATUS,Confidentiality status (flag)
0,dataflow,ESTAT:ISOC_SKS_ITSPS(1.0),Employed ICT specialists by sex,A,Annual,PC,Percentage,F,Females,AT,Austria,2004,NaN,22.1,NaN,be,"break in time series, estimated",NaN,NaN
1,dataflow,ESTAT:ISOC_SKS_ITSPS(1.0),Employed ICT specialists by sex,A,Annual,PC,Percentage,F,Females,AT,Austria,2005,NaN,20.0,NaN,be,"break in time series, estimated",NaN,NaN
2,dataflow,ESTAT:ISOC_SKS_ITSPS(1.0),Employed ICT specialists by sex,A,Annual,PC,Percentage,F,Females,AT,Austria,2006,NaN,19.7,NaN,e,estimated,NaN,NaN
3,dataflow,ESTAT:ISOC_SKS_ITSPS(1.0),Employed ICT specialists by sex,A,Annual,PC,Percentage,F,Females,AT,Austria,2007,NaN,20.9,NaN,be,"break in time series, estimated",NaN,NaN
4,dataflow,ESTAT:ISOC_SKS_ITSPS(1.0),Employed ICT specialists by sex,A,Annual,PC,Percentage,F,Females,AT,Austria,2008,NaN,17.6,NaN,e,estimated,NaN,NaN

================ DATASET 10 ================
Dataset: 1376 filas × 9 columnas

,DATAFLOW,LAST UPDATE,freq,unit,geo,TIME_PERIOD,OBS_VALUE,OBS_FLAG,CONF_STATUS
0,ESTAT:ISOC_SKS_ITSPT(1.0),14/04/25 23:00:00,Annual,Percentage of total employment,Austria,2004,2.9,be,NaN
1,ESTAT:ISOC_SKS_ITSPT(1.0),14/04/25 23:00:00,Annual,Percentage of total employment,Austria,2005,3.1,be,NaN
2,ESTAT:ISOC_SKS_ITSPT(1.0),14/04/25 23:00:00,Annual,Percentage of total employment,Austria,2006,3.3,e,NaN
3,ESTAT:ISOC_SKS_ITSPT(1.0),14/04/25 23:00:00,Annual,Percentage of total employment,Austria,2007,3.3,be,NaN
4,ESTAT:ISOC_SKS_ITSPT(1.0),14/04/25 23:00:00,Annual,Percentage of total employment,Austria,2008,3.3,e,NaN

================ DATASET 11 ================
Dataset: 23180 filas × 23 columnas

,STRUCTURE,STRUCTURE_ID,STRUCTURE_NAME,freq,Time frequency,size_emp,Size classes in number of persons employed,nace_r2,Statistical classification of economic activities in the European Community (NACE Rev. 2),indic_is,Information society indicator,unit,Unit of measure,geo,Geopolitical entity (reporting),TIME_PERIOD,Time,OBS_VALUE,Observation value,OBS_FLAG,Observation status (Flag) V2 structure,CONF_STATUS,Confidentiality status (flag)
0,dataflow,ESTAT:ISOC_SKE_ITSPEN2(1.0),Enterprises that employ ICT specialists by NAC...,A,Annual,GE10,10 persons employed or more,C,Manufacturing,E_ITSP2,Enterprise employed ICT/IT specialists (reduce...,PC_ENT,Percentage of enterprises,AL,Albania,2022,NaN,11.22,NaN,b,break in time series,NaN,NaN
1,dataflow,ESTAT:ISOC_SKE_ITSPEN2(1.0),Enterprises that employ ICT specialists by NAC...,A,Annual,GE10,10 persons employed or more,C,Manufacturing,E_ITSP2,Enterprise employed ICT/IT specialists (reduce...,PC_ENT,Percentage of enterprises,AT,Austria,2012,NaN,35.12,NaN,NaN,NaN,NaN,NaN
2,dataflow,ESTAT:ISOC_SKE_ITSPEN2(1.0),Enterprises that employ ICT specialists by NAC...,A,Annual,GE10,10 persons employed or more,C,Manufacturing,E_ITSP2,Enterprise employed ICT/IT specialists (reduce...,PC_ENT,Percentage of enterprises,AT,Austria,2014,NaN,31.01,NaN,NaN,NaN,NaN,NaN
3,dataflow,ESTAT:ISOC_SKE_ITSPEN2(1.0),Enterprises that employ ICT specialists by NAC...,A,Annual,GE10,10 persons employed or more,C,Manufacturing,E_ITSP2,Enterprise employed ICT/IT specialists (reduce...,PC_ENT,Percentage of enterprises,AT,Austria,2015,NaN,31.44,NaN,NaN,NaN,NaN,NaN
4,dataflow,ESTAT:ISOC_SKE_ITSPEN2(1.0),Enterprises that employ ICT specialists by NAC...,A,Annual,GE10,10 persons employed or more,C,Manufacturing,E_ITSP2,Enterprise employed ICT/IT specialists (reduce...,PC_ENT,Percentage of enterprises,AT,Austria,2016,NaN,35.22,NaN,NaN,NaN,NaN,NaN

#### **2. HOMOGENEIZACIÓN EN EL NOMBRADO DE COLUMNAS**

- En esta sección se estandarizan los nombres de las columnas para garantizar consistencia y facilitar su uso en las fases posteriores del análisis.
- Primero, se normalizan los nombres al formato `snake_case`, eliminando espacios y caracteres especiales.
- Posteriormente, se renombran aquellas variables con nomenclatura ambigua para mejorar su claridad semántica (por ejemplo, `Date&Time` se renombra a `date_time`).
- Este proceso mejora la legibilidad del dataset y facilita su manipulación en el flujo de limpieza y análisis.

In [147]:
def normalizar_nombres_columnas(lista_columnas, mostrar_resumen=True):
    """
    Normaliza los nombres de columnas a formato snake_case estándar.

    Transformaciones aplicadas:
    - Eliminación de espacios al inicio y final
    - Conversión de CamelCase y PascalCase a snake_case
    - Sustitución de caracteres no alfanuméricos por guión bajo (_)
    - Conversión a minúsculas
    - Eliminación de guiones bajos duplicados
    - Eliminación de guiones bajos al inicio y final

    Parámetros
    ----------
    lista_columnas : list of str
        Lista de nombres de columnas originales.

    mostrar_resumen : bool, default=True
        Si True, muestra un resumen de la transformación realizada.

    Returns
    -------
    list of str
        Lista de nombres normalizados en formato snake_case.

    Ejemplo
    -------
    >>> normalizar_nombres_columnas(["Date&Time", "UserID", "App Name"])
    ['date_time', 'user_id', 'app_name']
    """

    nombres_normalizados = []
    contador = {}

    for nombre in lista_columnas:

        original = nombre

        # quitar espacios
        limpia = nombre.strip()

        # eliminar acentos
        limpia = unicodedata.normalize("NFKD", limpia)
        limpia = limpia.encode("ascii", "ignore").decode("utf-8")

        # camelCase → snake_case
        limpia = re.sub(r'([a-z0-9])([A-Z])', r'\1_\2', limpia)

        # caracteres no alfanuméricos → _
        limpia = re.sub(r'[^0-9a-zA-Z]+', '_', limpia)

        # minúsculas
        limpia = limpia.lower()

        # quitar duplicados de _
        limpia = re.sub(r'_+', '_', limpia)

        # quitar _ extremos
        limpia = limpia.strip('_')

        # 🔹 asegurar unicidad
        if limpia in contador:
            contador[limpia] += 1
            limpia = f"{limpia}_{contador[limpia]}"
        else:
            contador[limpia] = 0

        nombres_normalizados.append(limpia)

    if mostrar_resumen:
        print("Normalización de nombres de columnas completada.")
        print(f"Columnas procesadas: {len(lista_columnas)}")
        print("Transformaciones aplicadas:")
        for original, nuevo in zip(lista_columnas, nombres_normalizados):
            if original != nuevo:
                print(f"  {original} → {nuevo}")

    return nombres_normalizados

In [148]:
for i, df in enumerate(dfs, start=1):
    print(f"\n================ DATASET {i} ================")
    df.columns = normalizar_nombres_columnas(df.columns)

================ DATASET 1 ================
Normalización de nombres de columnas completada.
Columnas procesadas: 13
Transformaciones aplicadas:

================ DATASET 2 ================
Normalización de nombres de columnas completada.
Columnas procesadas: 19
Transformaciones aplicadas:
  STRUCTURE → structure
  STRUCTURE_ID → structure_id
  STRUCTURE_NAME → structure_name
  Time frequency → time_frequency
  International Standard Classification of Occupations 2008 (ISCO-08) → international_standard_classification_of_occupations_2008_isco_08
  Unit of measure → unit_of_measure
  Geopolitical entity (reporting) → geopolitical_entity_reporting
  TIME_PERIOD → time_period
  Time → time
  OBS_VALUE → obs_value
  Observation value → observation_value
  OBS_FLAG → obs_flag
  Observation status (Flag) V2 structure → observation_status_flag_v2_structure
  CONF_STATUS → conf_status
  Confidentiality status (flag) → confidentiality_status_flag

================ DATASET 3 ================
Normalización de nombres de columnas completada.
Columnas procesadas: 23
Transformaciones aplicadas:
  STRUCTURE → structure
  STRUCTURE_ID → structure_id
  STRUCTURE_NAME → structure_name
  Time frequency → time_frequency
  Size classes in number of persons employed → size_classes_in_number_of_persons_employed
  Statistical classification of economic activities in the European Community (NACE Rev. 2) → statistical_classification_of_economic_activities_in_the_european_community_nace_rev_2
  Information society indicator → information_society_indicator
  Unit of measure → unit_of_measure
  Geopolitical entity (reporting) → geopolitical_entity_reporting
  TIME_PERIOD → time_period
  Time → time
  OBS_VALUE → obs_value
  Observation value → observation_value
  OBS_FLAG → obs_flag
  Observation status (Flag) V2 structure → observation_status_flag_v2_structure
  CONF_STATUS → conf_status
  Confidentiality status (flag) → confidentiality_status_flag

================ DATASET 4 ================
Normalización de nombres de columnas completada.
Columnas procesadas: 5
Transformaciones aplicadas:

================ DATASET 5 ================
Normalización de nombres de columnas completada.
Columnas procesadas: 17
Transformaciones aplicadas:
  STRUCTURE → structure
  STRUCTURE_ID → structure_id
  STRUCTURE_NAME → structure_name
  Time frequency → time_frequency
  Unit of measure → unit_of_measure
  Geopolitical entity (reporting) → geopolitical_entity_reporting
  TIME_PERIOD → time_period
  Time → time
  OBS_VALUE → obs_value
  Observation value → observation_value
  OBS_FLAG → obs_flag
  Observation status (Flag) V2 structure → observation_status_flag_v2_structure
  CONF_STATUS → conf_status
  Confidentiality status (flag) → confidentiality_status_flag

================ DATASET 6 ================
Normalización de nombres de columnas completada.
Columnas procesadas: 19
Transformaciones aplicadas:
  STRUCTURE → structure
  STRUCTURE_ID → structure_id
  STRUCTURE_NAME → structure_name
  Time frequency → time_frequency
  Unit of measure → unit_of_measure
  Age class → age_class
  Geopolitical entity (reporting) → geopolitical_entity_reporting
  TIME_PERIOD → time_period
  Time → time
  OBS_VALUE → obs_value
  Observation value → observation_value
  OBS_FLAG → obs_flag
  Observation status (Flag) V2 structure → observation_status_flag_v2_structure
  CONF_STATUS → conf_status
  Confidentiality status (flag) → confidentiality_status_flag

================ DATASET 7 ================
Normalización de nombres de columnas completada.
Columnas procesadas: 19
Transformaciones aplicadas:
  STRUCTURE → structure
  STRUCTURE_ID → structure_id
  STRUCTURE_NAME → structure_name
  Time frequency → time_frequency
  Unit of measure → unit_of_measure
  International Standard Classification of Education (ISCED 2011) → international_standard_classification_of_education_isced_2011
  Geopolitical entity (reporting) → geopolitical_entity_reporting
  TIME_PERIOD → time_period
  Time → time
  OBS_VALUE → obs_value
  Observation value → observation_value
  OBS_FLAG → obs_flag
  Observation status (Flag) V2 structure → observation_status_flag_v2_structure
  CONF_STATUS → conf_status
  Confidentiality status (flag) → confidentiality_status_flag

================ DATASET 8 ================
Normalización de nombres de columnas completada.
Columnas procesadas: 19
Transformaciones aplicadas:
  STRUCTURE → structure
  STRUCTURE_ID → structure_id
  STRUCTURE_NAME → structure_name
  Time frequency → time_frequency
  Statistical classification of economic activities in the European Community (NACE Rev. 2) → statistical_classification_of_economic_activities_in_the_european_community_nace_rev_2
  Unit of measure → unit_of_measure
  Geopolitical entity (reporting) → geopolitical_entity_reporting
  TIME_PERIOD → time_period
  Time → time
  OBS_VALUE → obs_value
  Observation value → observation_value
  OBS_FLAG → obs_flag
  Observation status (Flag) V2 structure → observation_status_flag_v2_structure
  CONF_STATUS → conf_status
  Confidentiality status (flag) → confidentiality_status_flag

================ DATASET 9 ================
Normalización de nombres de columnas completada.
Columnas procesadas: 19
Transformaciones aplicadas:
  STRUCTURE → structure
  STRUCTURE_ID → structure_id
  STRUCTURE_NAME → structure_name
  Time frequency → time_frequency
  Unit of measure → unit_of_measure
  Sex → sex_1
  Geopolitical entity (reporting) → geopolitical_entity_reporting
  TIME_PERIOD → time_period
  Time → time
  OBS_VALUE → obs_value
  Observation value → observation_value
  OBS_FLAG → obs_flag
  Observation status (Flag) V2 structure → observation_status_flag_v2_structure
  CONF_STATUS → conf_status
  Confidentiality status (flag) → confidentiality_status_flag

================ DATASET 10 ================
Normalización de nombres de columnas completada.
Columnas procesadas: 9
Transformaciones aplicadas:
  DATAFLOW → dataflow
  LAST UPDATE → last_update
  TIME_PERIOD → time_period
  OBS_VALUE → obs_value
  OBS_FLAG → obs_flag
  CONF_STATUS → conf_status

================ DATASET 11 ================
Normalización de nombres de columnas completada.
Columnas procesadas: 23
Transformaciones aplicadas:
  STRUCTURE → structure
  STRUCTURE_ID → structure_id
  STRUCTURE_NAME → structure_name
  Time frequency → time_frequency
  Size classes in number of persons employed → size_classes_in_number_of_persons_employed
  Statistical classification of economic activities in the European Community (NACE Rev. 2) → statistical_classification_of_economic_activities_in_the_european_community_nace_rev_2
  Information society indicator → information_society_indicator
  Unit of measure → unit_of_measure
  Geopolitical entity (reporting) → geopolitical_entity_reporting
  TIME_PERIOD → time_period
  Time → time
  OBS_VALUE → obs_value
  Observation value → observation_value
  OBS_FLAG → obs_flag
  Observation status (Flag) V2 structure → observation_status_flag_v2_structure
  CONF_STATUS → conf_status
  Confidentiality status (flag) → confidentiality_status_flag

#### **3. ELIMINACIÓN DE COLUMNAS NO INFORMATIVAS**

- En esta sección se identifican y eliminan variables que no aportan información relevante para el análisis y que pueden introducir ruido en el dataset.
- Primero, se eliminan aquellas columnas completamente nulas (100% valores faltantes), ya que no contienen información utilizable: `eliminar_columnas_vacias`.
- Posteriormente, se eliminan las columnas constantes, es decir, aquellas que presentan un único valor en todas las filas y no aportan variabilidad ni capacidad explicativa `eliminar_columnas_constantes`.
- Por último, se eliminan aquellas columnas no consideras de interés para el análisis de datos: `eliminar_columnas_sin_interes`.
- Este proceso permite reducir la dimensionalidad del dataset y simplificar las fases posteriores de exploración, análisis y visualización.

In [149]:
def eliminar_columnas_vacias(df, mostrar_resumen=True):
    """
    Elimina columnas que contienen únicamente valores nulos.

    Parámetros
    ----------
    df : pandas.DataFrame
        DataFrame a procesar.

    mostrar_resumen : bool, default=True
        Si True, muestra qué columnas se han eliminado.

    Returns
    -------
    pandas.DataFrame
        DataFrame sin columnas completamente nulas.
    """

    columnas_vacias = df.columns[df.isnull().all()]

    if mostrar_resumen and len(columnas_vacias) > 0:
        print(f"Columnas eliminadas ({len(columnas_vacias)}):")
        for col in columnas_vacias:
            print(f"  - {col}")

    df = df.drop(columns=columnas_vacias)

    return df

In [150]:
for i, df in enumerate(dfs):
    print(f"\n===== DF{i+1} =====")
    dfs[i] = eliminar_columnas_vacias(df)

===== DF1 =====

===== DF2 =====
Columnas eliminadas (6):
  - time
  - observation_value
  - obs_flag
  - observation_status_flag_v2_structure
  - conf_status
  - confidentiality_status_flag

===== DF3 =====
Columnas eliminadas (4):
  - time
  - observation_value
  - conf_status
  - confidentiality_status_flag

===== DF4 =====

===== DF5 =====
Columnas eliminadas (6):
  - time
  - observation_value
  - obs_flag
  - observation_status_flag_v2_structure
  - conf_status
  - confidentiality_status_flag

===== DF6 =====
Columnas eliminadas (4):
  - time
  - observation_value
  - conf_status
  - confidentiality_status_flag

===== DF7 =====
Columnas eliminadas (4):
  - time
  - observation_value
  - conf_status
  - confidentiality_status_flag

===== DF8 =====
Columnas eliminadas (4):
  - time
  - observation_value
  - conf_status
  - confidentiality_status_flag

===== DF9 =====
Columnas eliminadas (4):
  - time
  - observation_value
  - conf_status
  - confidentiality_status_flag

===== DF10 =====
Columnas eliminadas (1):
  - conf_status

===== DF11 =====
Columnas eliminadas (2):
  - time
  - observation_value

In [151]:
def eliminar_columnas_constantes(df, excepciones=None, mostrar_resumen=True):
    """
    Elimina columnas que contienen un único valor único en todo el DataFrame.

    Este tipo de columnas no aporta información analítica, ya que no presentan
    variabilidad entre observaciones. Pueden aparecer frecuentemente en datasets
    estadísticos o administrativos como metadatos constantes.

    Parámetros
    ----------
    df : pandas.DataFrame
        DataFrame a procesar.

    excepciones : list, default=None
        Lista de columnas que no deben eliminarse aunque tengan un único valor.
        Útil para mantener variables estructurales como 'unit'.

    mostrar_resumen : bool, default=True
        Si True, muestra por consola las columnas que han sido eliminadas.

    Returns
    -------
    pandas.DataFrame
        DataFrame sin columnas constantes (excepto las indicadas en excepciones).

    Ejemplo
    -------
    >>> eliminar_columnas_constantes(df, excepciones=["unit"])
    Columnas constantes eliminadas (2):
      - dataset
      - freq
    """
    
    if excepciones is None:
        excepciones = []

    columnas_constantes = [
        col for col in df.columns
        if df[col].nunique(dropna=False) == 1 and col not in excepciones
    ]

    if mostrar_resumen and len(columnas_constantes) > 0:
        print(f"Columnas constantes eliminadas ({len(columnas_constantes)}):")
        for col in columnas_constantes:
            print(f"  - {col}")

    df = df.drop(columns=columnas_constantes)

    return df

In [152]:
for i, df in enumerate(dfs):
    print(f"\n===== DF{i+1} =====")
    dfs[i] = eliminar_columnas_constantes(df, excepciones=["unit_of_measure", "size_emp", "size_classes_in_number_of_persons_employed"])

===== DF1 =====

===== DF2 =====
Columnas constantes eliminadas (6):
  - structure
  - structure_id
  - structure_name
  - freq
  - time_frequency
  - unit

===== DF3 =====
Columnas constantes eliminadas (9):
  - structure
  - structure_id
  - structure_name
  - freq
  - time_frequency
  - nace_r2
  - statistical_classification_of_economic_activities_in_the_european_community_nace_rev_2
  - indic_is
  - information_society_indicator

===== DF4 =====

===== DF5 =====
Columnas constantes eliminadas (6):
  - structure
  - structure_id
  - structure_name
  - freq
  - time_frequency
  - unit

===== DF6 =====
Columnas constantes eliminadas (5):
  - structure
  - structure_id
  - structure_name
  - freq
  - time_frequency

===== DF7 =====
Columnas constantes eliminadas (5):
  - structure
  - structure_id
  - structure_name
  - freq
  - time_frequency

===== DF8 =====
Columnas constantes eliminadas (5):
  - structure
  - structure_id
  - structure_name
  - freq
  - time_frequency

===== DF9 =====
Columnas constantes eliminadas (5):
  - structure
  - structure_id
  - structure_name
  - freq
  - time_frequency

===== DF10 =====
Columnas constantes eliminadas (3):
  - dataflow
  - last_update
  - freq

===== DF11 =====
Columnas constantes eliminadas (7):
  - structure
  - structure_id
  - structure_name
  - freq
  - time_frequency
  - indic_is
  - information_society_indicator

In [153]:
def eliminar_columnas_sin_interes(df, mostrar_resumen=True):
    """
    Elimina columnas que no se consideran relevantes para el análisis.

    Incluye:
    - Flags y metadatos típicos (calidad/estado/confidencialidad).
    - Dimensiones/códigos que no se van a explotar en este análisis (ocupación, educación, sector, unidad).

    Nota: esta función asume que los nombres de columnas ya están normalizados
    (snake_case) en pasos previos del pipeline.

    Parameters
    ----------
    df : pandas.DataFrame
        DataFrame de entrada.
    mostrar_resumen : bool, default=True
        Si True, imprime qué columnas se eliminan.

    Returns
    -------
    pandas.DataFrame
        DataFrame sin las columnas eliminadas.
    """

    columnas_a_eliminar = [
        # --- FLAGS / METADATA ---
        "obs_flag",
        "observation_status_flag_v2_structure",
        "conf_status",
        "confidentiality_status_flag",

        # --- DIMENSIONES (NO EN ALCANCE) ---
        "isco08",
        "isced11",
        "nace_r2",
        "unit",
    ]

    cols_drop = [c for c in columnas_a_eliminar if c in df.columns]

    if mostrar_resumen:
        print(f"Columnas eliminadas ({len(cols_drop)}): {cols_drop}")

    return df.drop(columns=cols_drop, errors="ignore")

In [154]:
for i, df in enumerate(dfs):
    print(f"\n===== DF{i+1} =====")
    dfs[i] = eliminar_columnas_sin_interes(df)

===== DF1 =====
Columnas eliminadas (0): []

===== DF2 =====
Columnas eliminadas (1): ['isco08']

===== DF3 =====
Columnas eliminadas (3): ['obs_flag', 'observation_status_flag_v2_structure', 'unit']

===== DF4 =====
Columnas eliminadas (0): []

===== DF5 =====
Columnas eliminadas (0): []

===== DF6 =====
Columnas eliminadas (3): ['obs_flag', 'observation_status_flag_v2_structure', 'unit']

===== DF7 =====
Columnas eliminadas (4): ['obs_flag', 'observation_status_flag_v2_structure', 'isced11', 'unit']

===== DF8 =====
Columnas eliminadas (4): ['obs_flag', 'observation_status_flag_v2_structure', 'nace_r2', 'unit']

===== DF9 =====
Columnas eliminadas (3): ['obs_flag', 'observation_status_flag_v2_structure', 'unit']

===== DF10 =====
Columnas eliminadas (2): ['obs_flag', 'unit']

===== DF11 =====
Columnas eliminadas (6): ['obs_flag', 'observation_status_flag_v2_structure', 'conf_status', 'confidentiality_status_flag', 'nace_r2', 'unit']

#### **4. TRATAMIENTO DE VALORES NULOS**

- En esta sección se gestionan los valores nulos del dataset para garantizar la consistencia de la información antes de iniciar el análisis exploratorio.
- En primer lugar, se eliminan las filas donde la variable principal de análisis (`obs_value`) presenta valores nulos, ya que estas observaciones no aportan información útil para el estudio del indicador.
- En el resto de variables categóricas, los valores nulos se sustituyen por la categoría `Unknown`, permitiendo mantener las observaciones sin introducir sesgos en el análisis.
- Los nulos en las variables numéricas, si los hubiera, se mantienen.
- Este procedimiento asegura que las métricas analizadas se basen únicamente en datos válidos, al mismo tiempo que se preserva la mayor cantidad posible de información en las variables descriptivas.

In [155]:
def tratamiento_nulos(df, col_valor="obs_value", fill_unknown="Unknown", mostrar_resumen=True):
    """
    Trata los nulos con una regla dirigida a datasets tipo Eurostat/indicadores:

    Reglas
    ------
    1) Elimina filas donde la columna principal de análisis (col_valor) sea nula.
       (Ej: 'obs_value' suele ser el valor del indicador).
    2) En el resto de columnas categóricas (object/category/string), rellena nulos con 'Unknown'.
    3) No modifica nulos en columnas numéricas distintas de col_valor (se conservan tal cual).

    Parámetros
    ----------
    df : pandas.DataFrame
        DataFrame de entrada.
    col_valor : str, default="obs_value"
        Nombre de la columna cuyo nulo implica eliminación de la fila.
    fill_unknown : str, default="Unknown"
        Valor con el que se rellenan los nulos en columnas categóricas.
    mostrar_resumen : bool, default=True
        Si True, imprime un resumen de filas eliminadas y nulos rellenados.

    Returns
    -------
    pandas.DataFrame
        DataFrame tras:
        - eliminar filas con nulos en col_valor
        - rellenar nulos en categóricas con fill_unknown

    Nota
    ----
    Para actualizar el dataframe:
    >>> df = tratamiento_nulos(df, col_valor="obs_value")
    """

    filas_iniciales = df.shape[0]

    # eliminar filas con nulos en columna valor SOLO si existe
    if col_valor in df.columns:
        nulos_valor = df[col_valor].isna().sum()
        df = df.dropna(subset=[col_valor]).copy()
        filas_eliminadas = filas_iniciales - df.shape[0]
    else:
        filas_eliminadas = 0
        if mostrar_resumen:
            print(f"La columna '{col_valor}' no existe en este dataset")

    # rellenar categóricas
    cols_cat = df.select_dtypes(include=["object","category"]).columns
    df[cols_cat] = df[cols_cat].fillna("Unknown")

    if mostrar_resumen:
        print("Tratamiento de nulos completado")
        print(f"Filas iniciales: {filas_iniciales}")
        print(f"Filas eliminadas por nulos en '{col_valor}': {filas_eliminadas}")
        print(f"Filas finales: {df.shape[0]}")

    return df

In [156]:
for i, df in enumerate(dfs):
    print(f"\n===== DF{i+1} =====")
    dfs[i] = tratamiento_nulos(df, col_valor="obs_value")

===== DF1 =====
La columna 'obs_value' no existe en este dataset
Tratamiento de nulos completado
Filas iniciales: 944
Filas eliminadas por nulos en 'obs_value': 0
Filas finales: 944

===== DF2 =====
Tratamiento de nulos completado
Filas iniciales: 4533
Filas eliminadas por nulos en 'obs_value': 0
Filas finales: 4533

===== DF3 =====
Tratamiento de nulos completado
Filas iniciales: 3253
Filas eliminadas por nulos en 'obs_value': 17
Filas finales: 3236

===== DF4 =====
La columna 'obs_value' no existe en este dataset
Tratamiento de nulos completado
Filas iniciales: 120
Filas eliminadas por nulos en 'obs_value': 0
Filas finales: 120

===== DF5 =====
Tratamiento de nulos completado
Filas iniciales: 7239
Filas eliminadas por nulos en 'obs_value': 0
Filas finales: 7239

===== DF6 =====
Tratamiento de nulos completado
Filas iniciales: 2752
Filas eliminadas por nulos en 'obs_value': 0
Filas finales: 2752

===== DF7 =====
Tratamiento de nulos completado
Filas iniciales: 3146
Filas eliminadas por nulos en 'obs_value': 236
Filas finales: 2910

===== DF8 =====
Tratamiento de nulos completado
Filas iniciales: 40900
Filas eliminadas por nulos en 'obs_value': 16848
Filas finales: 24052

===== DF9 =====
Tratamiento de nulos completado
Filas iniciales: 2752
Filas eliminadas por nulos en 'obs_value': 18
Filas finales: 2734

===== DF10 =====
Tratamiento de nulos completado
Filas iniciales: 1376
Filas eliminadas por nulos en 'obs_value': 0
Filas finales: 1376

===== DF11 =====
Tratamiento de nulos completado
Filas iniciales: 23180
Filas eliminadas por nulos en 'obs_value': 2691
Filas finales: 20489

#### **5. PREPARACIÓN DEL DATASET DE SKILLS**

- En esta sección se prepara el dataset de ofertas de empleo para analizar las habilidades demandadas en el mercado laboral tecnológico.
- Primero, se crea una copia del dataset original y se seleccionan únicamente las variables relevantes para el análisis (`job_title`, `seniority_level`, `status`, `industry`, `company_size` y `skills`).
- Posteriormente, se eliminan las observaciones donde la lista de habilidades está vacía, ya que no aportan información sobre competencias requeridas.
- Finalmente, se transforma la columna `skills` para que cada habilidad aparezca en una fila independiente, generando así un dataset estructurado que facilita el análisis de frecuencia y distribución de habilidades.

In [157]:
def preparar_skills_dataset(df, fill_unknown="Unknown"):
    """
    Prepara un dataset de ofertas de empleo para analizar skills.

    Procedimiento
    -------------
    1. Trabaja sobre una copia del DataFrame original.
    2. Elimina filas donde la columna 'skills' esté vacía o sea nula.
    3. Conserva únicamente las columnas relevantes:
       job_title, seniority_level, status, industry, company_size y skills.
    4. Normaliza la columna 'company_size':
       - elimina separadores de miles
       - convierte a numérico cuando es posible
       - valores no convertibles se sustituyen por 'Unknown'.
    5. Rellena valores nulos en columnas categóricas con 'Unknown'.
    6. Genera un nuevo DataFrame donde cada skill ocupa una fila
       utilizando explode().

    Parameters
    ----------
    df : pandas.DataFrame
        DataFrame de entrada con las ofertas de empleo.
    fill_unknown : str, default="Unknown"
        Valor utilizado para rellenar nulos en columnas categóricas
        o valores no interpretables.

    Returns
    -------
    pandas.DataFrame
        Nuevo DataFrame donde cada fila representa una skill individual.
    """

    # copiar dataframe
    df2 = df.copy()

    # eliminar filas sin skills
    df2 = df2[df2["skills"].notna()]
    df2 = df2[df2["skills"].astype(str).str.strip().ne("")]
    df2 = df2[df2["skills"].astype(str).str.strip().ne("[]")]

    # quedarse con columnas relevantes
    columnas = [
        "job_title",
        "seniority_level",
        "status",
        "industry",
        "company_size",
        "skills"
    ]
    df2 = df2[columnas].copy()

    # convertir skills a lista
    df2["skills"] = df2["skills"].astype(str).apply(ast.literal_eval)

    # normalizar company_size
    df2["company_size"] = pd.to_numeric(
        df2["company_size"].astype(str).str.replace(",", "", regex=False),
        errors="coerce"
    ).fillna(fill_unknown)

    # rellenar nulos en categóricas
    cols_cat = df2.select_dtypes(include=["object"]).columns
    df2[cols_cat] = df2[cols_cat].fillna(fill_unknown)

    # una skill por fila
    df_skills = df2.explode("skills").copy()
    df_skills["skills"] = df_skills["skills"].astype(str).str.lower().str.strip()

    # eliminar skills vacías o nulas
    df_skills = df_skills[(df_skills["skills"] != "") & (df_skills["skills"] != "nan")]

    return df_skills

In [158]:
df1_skills = preparar_skills_dataset(df1)
df1_skills.head()

,job_title,seniority_level,status,industry,company_size,skills
0,data scientist,senior,hybrid,Retail,Unknown,spark
0,data scientist,senior,hybrid,Retail,Unknown,r
0,data scientist,senior,hybrid,Retail,Unknown,python
0,data scientist,senior,hybrid,Retail,Unknown,scala
0,data scientist,senior,hybrid,Retail,Unknown,machine learning

#### **6. LIMPIEZA DE VARIABLES CATEGÓRICAS**

- En esta sección se estandariza el formato de las variables categóricas.
- Se eliminan espacios al inicio y al final de los valores y se aplica un formato homogéneo de capitalización.
- Este proceso garantiza la consistencia de las categorías y evita la duplicación de valores equivalentes con distinta representación.

In [159]:
def limpiar_categoricas(df, columnas=None):
    """
    Limpia variables categóricas eliminando espacios y unificando el formato del texto.

    Aplica .str.strip().str.capitalize() para garantizar consistencia en las categorías.

    Parámetros
    ----------
    df : pandas.DataFrame
        DataFrame a procesar.

    columnas : list, default=None
        Columnas a limpiar. Si es None, se aplicará a todas las columnas categóricas.

    Devuelve
    --------
    pandas.DataFrame
        DataFrame con las variables categóricas limpias.
    """

    # Si no se especifican columnas, detectar todas las categóricas
    if columnas is None:
        columnas = df.select_dtypes(include="O").columns

    # Aplicar limpieza básica
    for col in columnas:
        df[col] = df[col].str.strip().str.upper()

    return df

In [160]:
for df in dfs:
    limpiar_categoricas(df)

#### **7. AGRUPACIÓN Y SIMPLIFICACIÓN DE VARIABLES CATEGÓRICAS**

- En esta sección se simplifican y agrupan algunas variables categóricas para facilitar su interpretación en el análisis posterior.
- Primero, se renombran columnas con nombres excesivamente largos por etiquetas más intuitivas (`occupation`, `education`, `sector`).
- Posteriormente, se generan nuevas variables agregadas que reducen el número de categorías, como `company_size_group`, `education_group` o `sector_group`.
- Este proceso permite trabajar con dimensiones analíticas más claras y comparables entre los diferentes datasets.

In [162]:
def aplicar_agrupaciones(df):
    """
    Aplica simplificaciones y agrupaciones a variables categóricas del dataset.

    Transformaciones realizadas:
    - Renombrado de columnas largas a nombres más intuitivos (`occupation`, `education`, `sector`).
    - Agrupación del tamaño de empresa en categorías (`company_size_group`).
    - Simplificación de textos en ocupación y nivel educativo.
    - Creación de grupos agregados de sector económico (`sector_group`).

    Devuelve
    --------
    pandas.DataFrame
        DataFrame con las nuevas variables derivadas para facilitar el análisis.
    """

    cols_iniciales = set(df.columns)

    # renombrar columnas largas a nombres más intuitivos (si existen)
    df = df.rename(columns={
        "international_standard_classification_of_occupations_2008_isco_08": "occupation",
        "international_standard_classification_of_education_isced_2011": "education",
        "statistical_classification_of_economic_activities_in_the_european_community_nace_rev_2": "sector",
    })

    # company size (numérico) -> grupo
    if "company_size" in df.columns:
        size = pd.to_numeric(df["company_size"], errors="coerce")
        df["company_size_group"] = pd.cut(
            size, [0, 50, 250, 1000, 5000, 1e9],
            labels=["STARTUP", "SME", "MID_SIZE", "LARGE", "ENTERPRISE"]
        )

    # occupation -> texto corto
    if "occupation" in df.columns:
        s = df["occupation"].astype(str)
        df["occupation_short"] = s

        df.loc[s.str.contains("SERVICE MANAGERS", na=False), "occupation_short"] = "ICT SERVICE MANAGERS"
        df.loc[s.str.contains("SOFTWARE AND APPLICATIONS DEVELOPERS", na=False), "occupation_short"] = "SOFTWARE & APP DEVELOPERS"
        df.loc[s.str.contains("DATABASE AND NETWORK PROFESSIONALS", na=False), "occupation_short"] = "DATABASE & NETWORK PROFESSIONALS"
        df.loc[s.str.contains("OPERATIONS AND USER SUPPORT TECHNICIANS", na=False), "occupation_short"] = "ICT OPS & SUPPORT TECHNICIANS"
        df.loc[s.str.contains("TELECOMMUNICATIONS AND BROADCASTING TECHNICIANS", na=False), "occupation_short"] = "TELECOM & BROADCAST TECHNICIANS"
        df.loc[s.str.contains("INSTALLERS AND REPAIRERS", na=False), "occupation_short"] = "ELECTRONICS & TELECOM INSTALLERS"
        df.loc[s.str.contains("OTHER INFORMATION AND COMMUNICATIONS TECHNOLOGY SPECIALISTS", na=False), "occupation_short"] = "OTHER ICT SPECIALISTS"

    # education -> texto corto + education_group
    if "education" in df.columns:
        s = df["education"].astype(str)
        df["education_short"] = s

        df.loc[s.str.contains("LESS THAN PRIMARY", na=False), "education_short"] = "ISCED 0_4 NON_TERTIARY"
        df.loc[s.str.contains("TERTIARY EDUCATION", na=False), "education_short"] = "ISCED 5_8 TERTIARY"
        df.loc[s.str.contains("NO RESPONSE", na=False), "education_short"] = "UNKNOWN"

        df["education_group"] = "UNKNOWN"
        df.loc[s.str.contains("TERTIARY", na=False), "education_group"] = "HIGHER_EDUCATION"
        df.loc[s.str.contains("LESS THAN PRIMARY", na=False), "education_group"] = "LOW_MEDIUM_EDUCATION"

    elif "isced11" in df.columns:
        df["education_group"] = df["isced11"].replace({
            "ED0-4": "LOW_MEDIUM_EDUCATION",
            "ED5-8": "HIGHER_EDUCATION",
            "NRP": "UNKNOWN"
        })

    # sector -> macrosector
    if "sector" in df.columns:
        s = df["sector"].astype(str)

        df["sector_group"] = "OTHER"
        df.loc[s.str.contains("AGRICULTURE|FORESTRY|FISHING|MINING|QUARRYING", na=False), "sector_group"] = "PRIMARY"
        df.loc[s.str.contains("MANUFACTUR|ELECTRICITY|GAS|STEAM|WATER SUPPLY|SEWERAGE|WASTE", na=False), "sector_group"] = "INDUSTRY"
        df.loc[s.str.contains("CONSTRUCTION", na=False), "sector_group"] = "CONSTRUCTION"
        df.loc[s.str.contains("WHOLESALE|RETAIL|TRANSPORTATION|STORAGE|ACCOMMODATION|FOOD SERVICE", na=False), "sector_group"] = "TRADE_TRANSPORT_HOSPITALITY"
        df.loc[s.str.contains("INFORMATION AND COMMUNICATION|TELECOMMUNICATIONS|COMPUTER PROGRAMMING|ICT", na=False), "sector_group"] = "ICT"
        df.loc[s.str.contains("FINANCIAL|INSURANCE", na=False), "sector_group"] = "FINANCE"
        df.loc[s.str.contains("REAL ESTATE", na=False), "sector_group"] = "REAL_ESTATE"
        df.loc[s.str.contains("PROFESSIONAL|SCIENTIFIC|TECHNICAL|LEGAL|ACCOUNTING|CONSULTANCY|RESEARCH|ADVERTISING", na=False), "sector_group"] = "PROFESSIONAL_SERVICES"
        df.loc[s.str.contains("ADMINISTRATIVE|SUPPORT SERVICE|RENTAL|LEASING|EMPLOYMENT|SECURITY", na=False), "sector_group"] = "ADMIN_SUPPORT"
        df.loc[s.str.contains("PUBLIC ADMINISTRATION|DEFENCE|EDUCATION|HUMAN HEALTH|SOCIAL WORK", na=False), "sector_group"] = "PUBLIC_SERVICES"
        df.loc[s.str.contains("NO RESPONSE", na=False), "sector_group"] = "UNKNOWN"

    # columnas nuevas creadas
    cols_finales = set(df.columns)
    cols_nuevas = cols_finales - cols_iniciales

    if cols_nuevas:
        print("Columnas creadas:", sorted(cols_nuevas))
    else:
        print("No se han creado nuevas columnas")

    return df

In [163]:
for i, df in enumerate(dfs):
    print(f"\n===== DF{i+1} =====")
    dfs[i] = aplicar_agrupaciones(df)

===== DF1 =====
Columnas creadas: ['company_size_group']

===== DF2 =====
Columnas creadas: ['occupation', 'occupation_short']

===== DF3 =====
No se han creado nuevas columnas

===== DF4 =====
No se han creado nuevas columnas

===== DF5 =====
No se han creado nuevas columnas

===== DF6 =====
No se han creado nuevas columnas

===== DF7 =====
Columnas creadas: ['education', 'education_group', 'education_short']

===== DF8 =====
Columnas creadas: ['sector', 'sector_group']

===== DF9 =====
No se han creado nuevas columnas

===== DF10 =====
No se han creado nuevas columnas

===== DF11 =====
Columnas creadas: ['sector', 'sector_group']

#### **8. EXPORTACIÓN DEL DATASET LIMPIO**

- En esta sección se exportan los datasets tras aplicar los procesos de limpieza, tratamiento de nulos y transformación de variables.
- Los datasets se guardan en formato `.csv` dentro del directorio `data/processed/`, siguiendo una estructura organizada del proyecto.
- Esta exportación garantiza la reutilización de los mismos sin necesidad de repetir las fases de preparación.

In [164]:
output_path_reviews = "

df2.to_csv(output_path_reviews, index=False)

print("Exportación completada correctamente:")
print(f"  - Reviews:        {output_path_reviews}")

SyntaxError: unterminated string literal (detected at line 1) (2822983241.py, line 1)