# **LIMPIEZA Y TRANSFORMACIÓN DE LOS DATOS**

Este notebook aplica las transformaciones de limpieza derivadas del EDA y realiza validaciones básicas para asegurar consistencia y calidad de los datos antes del análisis.

**Principios**
- Transformar y exportar el dataset limpio a `data/processed/`.
- Documentar cada transformación y su motivación.

In [40]:
import pandas as pd
import numpy as np
import regex as re
import unicodedata
import matplotlib.pyplot as plt
import seaborn as sns


pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
pd.set_option("display.width", None)

#### **1. CARGA DE LOS DATASETS**

- Importar los datasets originales que servirán como base para las fases de limpieza, corrección y transformación de los datos.
- Tras la carga, se realiza una verificación básica para confirmar la correcta lectura de los archivos, dimensiones y la estructura general.

In [41]:
path1 = "../data/raw/data_science_job_posts_2025.csv"
path2 = "../data/raw/Distribución de las ofertas de empleo tech según el tipo de profesión tecnológica.csv"
path3 = "../data/raw/empresas por tamaño que contratan empleados ICT.csv"
path4 = "../data/raw/eu_data_jobs_salaries.csv"
path5 = "../data/raw/Número o proporción de ofertas de empleo online que buscan especialistas tecnológicos (ICT).csv"
path6 = "../data/raw/porcentaje de especialistas empleados por edad.csv"
path7 = "../data/raw/porcentaje de especialistas empleados por nivel educativo.csv"
path8 = "../data/raw/porcentaje de especialistas empleados por sector.csv"
path9 = "../data/raw/porcentaje de especialistas empleados por sexo.csv"
path10 = "../data/raw/porcentaje_profesionales_tecnologia_empleo_total_europa.csv"
path11 = "../data/raw/sectores que contratan empleados ICT.csv"
df1 = pd.read_csv(path1)
df2 = pd.read_csv(path2)
df3 = pd.read_csv(path3)
df4 = pd.read_csv(path4)
df5 = pd.read_csv(path5)
df6 = pd.read_csv(path6)
df7 = pd.read_csv(path7)
df8 = pd.read_csv(path8)
df9 = pd.read_csv(path9)
df10 = pd.read_csv(path10)
df11 = pd.read_csv(path11)

In [42]:
dfs = [df1, df2, df3, df4, df5, df6, df7, df8, df9, df10, df11]

for i, df in enumerate(dfs, start=1):
    print(f"\n================ DATASET {i} ================")
    print(f"Dataset: {df.shape[0]} filas × {df.shape[1]} columnas")
    display(df.head())

================ DATASET 1 ================
Dataset: 944 filas × 13 columnas

,job_title,seniority_level,status,company,location,post_date,headquarter,industry,ownership,company_size,revenue,salary,skills
0,data scientist,senior,hybrid,company_003,"Grapevine, TX . Hybrid",17 days ago,"Bentonville, AR, US",Retail,Public,€352.44B,Public,"€100,472 - €200,938","['spark', 'r', 'python', 'scala', 'machine lea..."
1,data scientist,lead,hybrid,company_005,"Fort Worth, TX . Hybrid",15 days ago,"Detroit, MI, US",Manufacturing,Public,"155,030",€51.10B,"€118,733","['spark', 'r', 'python', 'sql', 'machine learn..."
2,data scientist,senior,on-site,company_007,"Austin, TX . Toronto, Ontario, Canada . Kirkla...",a month ago,"Redwood City, CA, US",Technology,Public,"25,930",€33.80B,"€94,987 - €159,559","['aws', 'git', 'python', 'docker', 'sql', 'mac..."
3,data scientist,senior,hybrid,company_008,"Chicago, IL . Scottsdale, AZ . Austin, TX . Hy...",8 days ago,"San Jose, CA, US",Technology,Public,"34,690",€81.71B,"€112,797 - €194,402","['sql', 'r', 'python']"
4,data scientist,NaN,on-site,company_009,On-site,3 days ago,"Stamford, CT, US",Finance,Private,"1,800",Private,"€114,172 - €228,337",[]

================ DATASET 2 ================
Dataset: 4533 filas × 19 columnas

,STRUCTURE,STRUCTURE_ID,STRUCTURE_NAME,freq,Time frequency,isco08,International Standard Classification of Occupations 2008 (ISCO-08),unit,Unit of measure,geo,Geopolitical entity (reporting),TIME_PERIOD,Time,OBS_VALUE,Observation value,OBS_FLAG,Observation status (Flag) V2 structure,CONF_STATUS,Confidentiality status (flag)
0,dataflow,ESTAT:ISOC_SK_OJA2(1.0),Distribution by occupation (ISCO-08) of the la...,Q,Quarterly,OC133,Information and communications technology serv...,PC,Percentage,AT,Austria,2019-Q4,NaN,2.5,NaN,NaN,NaN,NaN,NaN
1,dataflow,ESTAT:ISOC_SK_OJA2(1.0),Distribution by occupation (ISCO-08) of the la...,Q,Quarterly,OC133,Information and communications technology serv...,PC,Percentage,AT,Austria,2020-Q1,NaN,2.5,NaN,NaN,NaN,NaN,NaN
2,dataflow,ESTAT:ISOC_SK_OJA2(1.0),Distribution by occupation (ISCO-08) of the la...,Q,Quarterly,OC133,Information and communications technology serv...,PC,Percentage,AT,Austria,2020-Q2,NaN,2.4,NaN,NaN,NaN,NaN,NaN
3,dataflow,ESTAT:ISOC_SK_OJA2(1.0),Distribution by occupation (ISCO-08) of the la...,Q,Quarterly,OC133,Information and communications technology serv...,PC,Percentage,AT,Austria,2020-Q3,NaN,2.2,NaN,NaN,NaN,NaN,NaN
4,dataflow,ESTAT:ISOC_SK_OJA2(1.0),Distribution by occupation (ISCO-08) of the la...,Q,Quarterly,OC133,Information and communications technology serv...,PC,Percentage,AT,Austria,2020-Q4,NaN,2.2,NaN,NaN,NaN,NaN,NaN

================ DATASET 3 ================
Dataset: 3253 filas × 23 columnas

,STRUCTURE,STRUCTURE_ID,STRUCTURE_NAME,freq,Time frequency,size_emp,Size classes in number of persons employed,nace_r2,Statistical classification of economic activities in the European Community (NACE Rev. 2),indic_is,Information society indicator,unit,Unit of measure,geo,Geopolitical entity (reporting),TIME_PERIOD,Time,OBS_VALUE,Observation value,OBS_FLAG,Observation status (Flag) V2 structure,CONF_STATUS,Confidentiality status (flag)
0,dataflow,ESTAT:ISOC_SKE_ITSPE(1.0),Enterprises that employ ICT specialists by siz...,A,Annual,0-9,From 0 to 9 persons employed,C10-S951_X_K,"All activities (except agriculture, forestry a...",E_ITSP2,Enterprise employed ICT/IT specialists (reduce...,PC_ENT,Percentage of enterprises,DE,Germany,2022,NaN,6.33,NaN,NaN,NaN,NaN,NaN
1,dataflow,ESTAT:ISOC_SKE_ITSPE(1.0),Enterprises that employ ICT specialists by siz...,A,Annual,0-9,From 0 to 9 persons employed,C10-S951_X_K,"All activities (except agriculture, forestry a...",E_ITSP2,Enterprise employed ICT/IT specialists (reduce...,PC_ENT,Percentage of enterprises,DE,Germany,2024,NaN,7.10,NaN,NaN,NaN,NaN,NaN
2,dataflow,ESTAT:ISOC_SKE_ITSPE(1.0),Enterprises that employ ICT specialists by siz...,A,Annual,0-9,From 0 to 9 persons employed,C10-S951_X_K,"All activities (except agriculture, forestry a...",E_ITSP2,Enterprise employed ICT/IT specialists (reduce...,PC_ENT,Percentage of enterprises,ES,Spain,2017,NaN,3.27,NaN,NaN,NaN,NaN,NaN
3,dataflow,ESTAT:ISOC_SKE_ITSPE(1.0),Enterprises that employ ICT specialists by siz...,A,Annual,0-9,From 0 to 9 persons employed,C10-S951_X_K,"All activities (except agriculture, forestry a...",E_ITSP2,Enterprise employed ICT/IT specialists (reduce...,PC_ENT,Percentage of enterprises,ES,Spain,2018,NaN,2.89,NaN,NaN,NaN,NaN,NaN
4,dataflow,ESTAT:ISOC_SKE_ITSPE(1.0),Enterprises that employ ICT specialists by siz...,A,Annual,0-9,From 0 to 9 persons employed,C10-S951_X_K,"All activities (except agriculture, forestry a...",E_ITSP2,Enterprise employed ICT/IT specialists (reduce...,PC_ENT,Percentage of enterprises,ES,Spain,2019,NaN,2.85,NaN,NaN,NaN,NaN,NaN

================ DATASET 4 ================
Dataset: 120 filas × 5 columnas

   country currency                role  salary_min  salary_max
0  Austria      EUR        Data Analyst       35000       70000
1  Austria      EUR      Data Scientist       37000       85000
2  Austria      EUR    Business Analyst       35000       75000
3  Austria      EUR  IT Project Manager       40000       90000
4  Belgium      EUR        Data Analyst       35000       60000

================ DATASET 5 ================
Dataset: 7239 filas × 17 columnas

,STRUCTURE,STRUCTURE_ID,STRUCTURE_NAME,freq,Time frequency,unit,Unit of measure,geo,Geopolitical entity (reporting),TIME_PERIOD,Time,OBS_VALUE,Observation value,OBS_FLAG,Observation status (Flag) V2 structure,CONF_STATUS,Confidentiality status (flag)
0,dataflow,ESTAT:ISOC_SK_OJA1(1.0),Labour market demand for ICT specialists in on...,Q,Quarterly,PC,Percentage,AT,Austria,2019-Q4,NaN,11.9,NaN,NaN,NaN,NaN,NaN
1,dataflow,ESTAT:ISOC_SK_OJA1(1.0),Labour market demand for ICT specialists in on...,Q,Quarterly,PC,Percentage,AT,Austria,2020-Q1,NaN,12.0,NaN,NaN,NaN,NaN,NaN
2,dataflow,ESTAT:ISOC_SK_OJA1(1.0),Labour market demand for ICT specialists in on...,Q,Quarterly,PC,Percentage,AT,Austria,2020-Q2,NaN,12.9,NaN,NaN,NaN,NaN,NaN
3,dataflow,ESTAT:ISOC_SK_OJA1(1.0),Labour market demand for ICT specialists in on...,Q,Quarterly,PC,Percentage,AT,Austria,2020-Q3,NaN,13.6,NaN,NaN,NaN,NaN,NaN
4,dataflow,ESTAT:ISOC_SK_OJA1(1.0),Labour market demand for ICT specialists in on...,Q,Quarterly,PC,Percentage,AT,Austria,2020-Q4,NaN,14.8,NaN,NaN,NaN,NaN,NaN

================ DATASET 6 ================
Dataset: 2752 filas × 19 columnas

,STRUCTURE,STRUCTURE_ID,STRUCTURE_NAME,freq,Time frequency,unit,Unit of measure,age,Age class,geo,Geopolitical entity (reporting),TIME_PERIOD,Time,OBS_VALUE,Observation value,OBS_FLAG,Observation status (Flag) V2 structure,CONF_STATUS,Confidentiality status (flag)
0,dataflow,ESTAT:ISOC_SKS_ITSPA(1.0),Employed ICT specialists by age,A,Annual,PC,Percentage,Y15-34,From 15 to 34 years,AT,Austria,2004,NaN,48.4,NaN,be,"break in time series, estimated",NaN,NaN
1,dataflow,ESTAT:ISOC_SKS_ITSPA(1.0),Employed ICT specialists by age,A,Annual,PC,Percentage,Y15-34,From 15 to 34 years,AT,Austria,2005,NaN,49.2,NaN,be,"break in time series, estimated",NaN,NaN
2,dataflow,ESTAT:ISOC_SKS_ITSPA(1.0),Employed ICT specialists by age,A,Annual,PC,Percentage,Y15-34,From 15 to 34 years,AT,Austria,2006,NaN,48.0,NaN,e,estimated,NaN,NaN
3,dataflow,ESTAT:ISOC_SKS_ITSPA(1.0),Employed ICT specialists by age,A,Annual,PC,Percentage,Y15-34,From 15 to 34 years,AT,Austria,2007,NaN,47.3,NaN,be,"break in time series, estimated",NaN,NaN
4,dataflow,ESTAT:ISOC_SKS_ITSPA(1.0),Employed ICT specialists by age,A,Annual,PC,Percentage,Y15-34,From 15 to 34 years,AT,Austria,2008,NaN,48.5,NaN,e,estimated,NaN,NaN

================ DATASET 7 ================
Dataset: 3146 filas × 19 columnas

,STRUCTURE,STRUCTURE_ID,STRUCTURE_NAME,freq,Time frequency,unit,Unit of measure,isced11,International Standard Classification of Education (ISCED 2011),geo,Geopolitical entity (reporting),TIME_PERIOD,Time,OBS_VALUE,Observation value,OBS_FLAG,Observation status (Flag) V2 structure,CONF_STATUS,Confidentiality status (flag)
0,dataflow,ESTAT:ISOC_SKS_ITSPE(1.0),Employed ICT specialists by educational attain...,A,Annual,PC,Percentage,ED0-4,"Less than primary, primary, secondary and post...",AT,Austria,2004,NaN,63.2,NaN,be,"break in time series, estimated",NaN,NaN
1,dataflow,ESTAT:ISOC_SKS_ITSPE(1.0),Employed ICT specialists by educational attain...,A,Annual,PC,Percentage,ED0-4,"Less than primary, primary, secondary and post...",AT,Austria,2005,NaN,66.0,NaN,be,"break in time series, estimated",NaN,NaN
2,dataflow,ESTAT:ISOC_SKS_ITSPE(1.0),Employed ICT specialists by educational attain...,A,Annual,PC,Percentage,ED0-4,"Less than primary, primary, secondary and post...",AT,Austria,2006,NaN,64.9,NaN,be,"break in time series, estimated",NaN,NaN
3,dataflow,ESTAT:ISOC_SKS_ITSPE(1.0),Employed ICT specialists by educational attain...,A,Annual,PC,Percentage,ED0-4,"Less than primary, primary, secondary and post...",AT,Austria,2007,NaN,63.4,NaN,be,"break in time series, estimated",NaN,NaN
4,dataflow,ESTAT:ISOC_SKS_ITSPE(1.0),Employed ICT specialists by educational attain...,A,Annual,PC,Percentage,ED0-4,"Less than primary, primary, secondary and post...",AT,Austria,2008,NaN,67.1,NaN,e,estimated,NaN,NaN

================ DATASET 8 ================
Dataset: 40900 filas × 19 columnas

,STRUCTURE,STRUCTURE_ID,STRUCTURE_NAME,freq,Time frequency,nace_r2,Statistical classification of economic activities in the European Community (NACE Rev. 2),unit,Unit of measure,geo,Geopolitical entity (reporting),TIME_PERIOD,Time,OBS_VALUE,Observation value,OBS_FLAG,Observation status (Flag) V2 structure,CONF_STATUS,Confidentiality status (flag)
0,dataflow,ESTAT:ISOC_SKS_ITSPN2(1.0),Employed ICT specialists by NACE Rev. 2 activity,A,Annual,A,"Agriculture, forestry and fishing",PC_EMP,Percentage of total employment,AT,Austria,2008,NaN,NaN,NaN,bu,"break in time series, low reliability",NaN,NaN
1,dataflow,ESTAT:ISOC_SKS_ITSPN2(1.0),Employed ICT specialists by NACE Rev. 2 activity,A,Annual,A,"Agriculture, forestry and fishing",PC_EMP,Percentage of total employment,AT,Austria,2010,NaN,NaN,NaN,u,low reliability,NaN,NaN
2,dataflow,ESTAT:ISOC_SKS_ITSPN2(1.0),Employed ICT specialists by NACE Rev. 2 activity,A,Annual,A,"Agriculture, forestry and fishing",PC_EMP,Percentage of total employment,AT,Austria,2011,NaN,NaN,NaN,bu,"break in time series, low reliability",NaN,NaN
3,dataflow,ESTAT:ISOC_SKS_ITSPN2(1.0),Employed ICT specialists by NACE Rev. 2 activity,A,Annual,A,"Agriculture, forestry and fishing",PC_EMP,Percentage of total employment,AT,Austria,2012,NaN,NaN,NaN,u,low reliability,NaN,NaN
4,dataflow,ESTAT:ISOC_SKS_ITSPN2(1.0),Employed ICT specialists by NACE Rev. 2 activity,A,Annual,A,"Agriculture, forestry and fishing",PC_EMP,Percentage of total employment,AT,Austria,2013,NaN,NaN,NaN,u,low reliability,NaN,NaN

================ DATASET 9 ================
Dataset: 2752 filas × 19 columnas

,STRUCTURE,STRUCTURE_ID,STRUCTURE_NAME,freq,Time frequency,unit,Unit of measure,sex,Sex,geo,Geopolitical entity (reporting),TIME_PERIOD,Time,OBS_VALUE,Observation value,OBS_FLAG,Observation status (Flag) V2 structure,CONF_STATUS,Confidentiality status (flag)
0,dataflow,ESTAT:ISOC_SKS_ITSPS(1.0),Employed ICT specialists by sex,A,Annual,PC,Percentage,F,Females,AT,Austria,2004,NaN,22.1,NaN,be,"break in time series, estimated",NaN,NaN
1,dataflow,ESTAT:ISOC_SKS_ITSPS(1.0),Employed ICT specialists by sex,A,Annual,PC,Percentage,F,Females,AT,Austria,2005,NaN,20.0,NaN,be,"break in time series, estimated",NaN,NaN
2,dataflow,ESTAT:ISOC_SKS_ITSPS(1.0),Employed ICT specialists by sex,A,Annual,PC,Percentage,F,Females,AT,Austria,2006,NaN,19.7,NaN,e,estimated,NaN,NaN
3,dataflow,ESTAT:ISOC_SKS_ITSPS(1.0),Employed ICT specialists by sex,A,Annual,PC,Percentage,F,Females,AT,Austria,2007,NaN,20.9,NaN,be,"break in time series, estimated",NaN,NaN
4,dataflow,ESTAT:ISOC_SKS_ITSPS(1.0),Employed ICT specialists by sex,A,Annual,PC,Percentage,F,Females,AT,Austria,2008,NaN,17.6,NaN,e,estimated,NaN,NaN

================ DATASET 10 ================
Dataset: 1376 filas × 9 columnas

,DATAFLOW,LAST UPDATE,freq,unit,geo,TIME_PERIOD,OBS_VALUE,OBS_FLAG,CONF_STATUS
0,ESTAT:ISOC_SKS_ITSPT(1.0),14/04/25 23:00:00,Annual,Percentage of total employment,Austria,2004,2.9,be,NaN
1,ESTAT:ISOC_SKS_ITSPT(1.0),14/04/25 23:00:00,Annual,Percentage of total employment,Austria,2005,3.1,be,NaN
2,ESTAT:ISOC_SKS_ITSPT(1.0),14/04/25 23:00:00,Annual,Percentage of total employment,Austria,2006,3.3,e,NaN
3,ESTAT:ISOC_SKS_ITSPT(1.0),14/04/25 23:00:00,Annual,Percentage of total employment,Austria,2007,3.3,be,NaN
4,ESTAT:ISOC_SKS_ITSPT(1.0),14/04/25 23:00:00,Annual,Percentage of total employment,Austria,2008,3.3,e,NaN

================ DATASET 11 ================
Dataset: 23180 filas × 23 columnas

,STRUCTURE,STRUCTURE_ID,STRUCTURE_NAME,freq,Time frequency,size_emp,Size classes in number of persons employed,nace_r2,Statistical classification of economic activities in the European Community (NACE Rev. 2),indic_is,Information society indicator,unit,Unit of measure,geo,Geopolitical entity (reporting),TIME_PERIOD,Time,OBS_VALUE,Observation value,OBS_FLAG,Observation status (Flag) V2 structure,CONF_STATUS,Confidentiality status (flag)
0,dataflow,ESTAT:ISOC_SKE_ITSPEN2(1.0),Enterprises that employ ICT specialists by NAC...,A,Annual,GE10,10 persons employed or more,C,Manufacturing,E_ITSP2,Enterprise employed ICT/IT specialists (reduce...,PC_ENT,Percentage of enterprises,AL,Albania,2022,NaN,11.22,NaN,b,break in time series,NaN,NaN
1,dataflow,ESTAT:ISOC_SKE_ITSPEN2(1.0),Enterprises that employ ICT specialists by NAC...,A,Annual,GE10,10 persons employed or more,C,Manufacturing,E_ITSP2,Enterprise employed ICT/IT specialists (reduce...,PC_ENT,Percentage of enterprises,AT,Austria,2012,NaN,35.12,NaN,NaN,NaN,NaN,NaN
2,dataflow,ESTAT:ISOC_SKE_ITSPEN2(1.0),Enterprises that employ ICT specialists by NAC...,A,Annual,GE10,10 persons employed or more,C,Manufacturing,E_ITSP2,Enterprise employed ICT/IT specialists (reduce...,PC_ENT,Percentage of enterprises,AT,Austria,2014,NaN,31.01,NaN,NaN,NaN,NaN,NaN
3,dataflow,ESTAT:ISOC_SKE_ITSPEN2(1.0),Enterprises that employ ICT specialists by NAC...,A,Annual,GE10,10 persons employed or more,C,Manufacturing,E_ITSP2,Enterprise employed ICT/IT specialists (reduce...,PC_ENT,Percentage of enterprises,AT,Austria,2015,NaN,31.44,NaN,NaN,NaN,NaN,NaN
4,dataflow,ESTAT:ISOC_SKE_ITSPEN2(1.0),Enterprises that employ ICT specialists by NAC...,A,Annual,GE10,10 persons employed or more,C,Manufacturing,E_ITSP2,Enterprise employed ICT/IT specialists (reduce...,PC_ENT,Percentage of enterprises,AT,Austria,2016,NaN,35.22,NaN,NaN,NaN,NaN,NaN

#### **2. HOMOGENEIZACIÓN EN EL NOMBRADO DE COLUMNAS**

- En esta sección se estandarizan los nombres de las columnas para garantizar consistencia y facilitar su uso en las fases posteriores del análisis.
- Primero, se normalizan los nombres al formato `snake_case`, eliminando espacios y caracteres especiales.
- Posteriormente, se renombran aquellas variables con nomenclatura ambigua para mejorar su claridad semántica (por ejemplo, `Date&Time` se renombra a `date_time`).
- Este proceso mejora la legibilidad del dataset y facilita su manipulación en el flujo de limpieza y análisis.

In [43]:
def normalizar_nombres_columnas(lista_columnas, mostrar_resumen=True):
    """
    Normaliza los nombres de columnas a formato snake_case estándar.

    Transformaciones aplicadas:
    - Eliminación de espacios al inicio y final
    - Conversión de CamelCase y PascalCase a snake_case
    - Sustitución de caracteres no alfanuméricos por guión bajo (_)
    - Conversión a minúsculas
    - Eliminación de guiones bajos duplicados
    - Eliminación de guiones bajos al inicio y final

    Parámetros
    ----------
    lista_columnas : list of str
        Lista de nombres de columnas originales.

    mostrar_resumen : bool, default=True
        Si True, muestra un resumen de la transformación realizada.

    Returns
    -------
    list of str
        Lista de nombres normalizados en formato snake_case.

    Ejemplo
    -------
    >>> normalizar_nombres_columnas(["Date&Time", "UserID", "App Name"])
    ['date_time', 'user_id', 'app_name']
    """

    nombres_normalizados = []
    contador = {}

    for nombre in lista_columnas:

        original = nombre

        # quitar espacios
        limpia = nombre.strip()

        # eliminar acentos
        limpia = unicodedata.normalize("NFKD", limpia)
        limpia = limpia.encode("ascii", "ignore").decode("utf-8")

        # camelCase → snake_case
        limpia = re.sub(r'([a-z0-9])([A-Z])', r'\1_\2', limpia)

        # caracteres no alfanuméricos → _
        limpia = re.sub(r'[^0-9a-zA-Z]+', '_', limpia)

        # minúsculas
        limpia = limpia.lower()

        # quitar duplicados de _
        limpia = re.sub(r'_+', '_', limpia)

        # quitar _ extremos
        limpia = limpia.strip('_')

        # 🔹 asegurar unicidad
        if limpia in contador:
            contador[limpia] += 1
            limpia = f"{limpia}_{contador[limpia]}"
        else:
            contador[limpia] = 0

        nombres_normalizados.append(limpia)

    if mostrar_resumen:
        print("Normalización de nombres de columnas completada.")
        print(f"Columnas procesadas: {len(lista_columnas)}")
        print("Transformaciones aplicadas:")
        for original, nuevo in zip(lista_columnas, nombres_normalizados):
            if original != nuevo:
                print(f"  {original} → {nuevo}")

    return nombres_normalizados

In [44]:
for i, df in enumerate(dfs, start=1):
    print(f"\n================ DATASET {i} ================")
    df.columns = normalizar_nombres_columnas(df.columns)

================ DATASET 1 ================
Normalización de nombres de columnas completada.
Columnas procesadas: 13
Transformaciones aplicadas:

================ DATASET 2 ================
Normalización de nombres de columnas completada.
Columnas procesadas: 19
Transformaciones aplicadas:
  STRUCTURE → structure
  STRUCTURE_ID → structure_id
  STRUCTURE_NAME → structure_name
  Time frequency → time_frequency
  International Standard Classification of Occupations 2008 (ISCO-08) → international_standard_classification_of_occupations_2008_isco_08
  Unit of measure → unit_of_measure
  Geopolitical entity (reporting) → geopolitical_entity_reporting
  TIME_PERIOD → time_period
  Time → time
  OBS_VALUE → obs_value
  Observation value → observation_value
  OBS_FLAG → obs_flag
  Observation status (Flag) V2 structure → observation_status_flag_v2_structure
  CONF_STATUS → conf_status
  Confidentiality status (flag) → confidentiality_status_flag

================ DATASET 3 ================
Normalización de nombres de columnas completada.
Columnas procesadas: 23
Transformaciones aplicadas:
  STRUCTURE → structure
  STRUCTURE_ID → structure_id
  STRUCTURE_NAME → structure_name
  Time frequency → time_frequency
  Size classes in number of persons employed → size_classes_in_number_of_persons_employed
  Statistical classification of economic activities in the European Community (NACE Rev. 2) → statistical_classification_of_economic_activities_in_the_european_community_nace_rev_2
  Information society indicator → information_society_indicator
  Unit of measure → unit_of_measure
  Geopolitical entity (reporting) → geopolitical_entity_reporting
  TIME_PERIOD → time_period
  Time → time
  OBS_VALUE → obs_value
  Observation value → observation_value
  OBS_FLAG → obs_flag
  Observation status (Flag) V2 structure → observation_status_flag_v2_structure
  CONF_STATUS → conf_status
  Confidentiality status (flag) → confidentiality_status_flag

================ DATASET 4 ================
Normalización de nombres de columnas completada.
Columnas procesadas: 5
Transformaciones aplicadas:

================ DATASET 5 ================
Normalización de nombres de columnas completada.
Columnas procesadas: 17
Transformaciones aplicadas:
  STRUCTURE → structure
  STRUCTURE_ID → structure_id
  STRUCTURE_NAME → structure_name
  Time frequency → time_frequency
  Unit of measure → unit_of_measure
  Geopolitical entity (reporting) → geopolitical_entity_reporting
  TIME_PERIOD → time_period
  Time → time
  OBS_VALUE → obs_value
  Observation value → observation_value
  OBS_FLAG → obs_flag
  Observation status (Flag) V2 structure → observation_status_flag_v2_structure
  CONF_STATUS → conf_status
  Confidentiality status (flag) → confidentiality_status_flag

================ DATASET 6 ================
Normalización de nombres de columnas completada.
Columnas procesadas: 19
Transformaciones aplicadas:
  STRUCTURE → structure
  STRUCTURE_ID → structure_id
  STRUCTURE_NAME → structure_name
  Time frequency → time_frequency
  Unit of measure → unit_of_measure
  Age class → age_class
  Geopolitical entity (reporting) → geopolitical_entity_reporting
  TIME_PERIOD → time_period
  Time → time
  OBS_VALUE → obs_value
  Observation value → observation_value
  OBS_FLAG → obs_flag
  Observation status (Flag) V2 structure → observation_status_flag_v2_structure
  CONF_STATUS → conf_status
  Confidentiality status (flag) → confidentiality_status_flag

================ DATASET 7 ================
Normalización de nombres de columnas completada.
Columnas procesadas: 19
Transformaciones aplicadas:
  STRUCTURE → structure
  STRUCTURE_ID → structure_id
  STRUCTURE_NAME → structure_name
  Time frequency → time_frequency
  Unit of measure → unit_of_measure
  International Standard Classification of Education (ISCED 2011) → international_standard_classification_of_education_isced_2011
  Geopolitical entity (reporting) → geopolitical_entity_reporting
  TIME_PERIOD → time_period
  Time → time
  OBS_VALUE → obs_value
  Observation value → observation_value
  OBS_FLAG → obs_flag
  Observation status (Flag) V2 structure → observation_status_flag_v2_structure
  CONF_STATUS → conf_status
  Confidentiality status (flag) → confidentiality_status_flag

================ DATASET 8 ================
Normalización de nombres de columnas completada.
Columnas procesadas: 19
Transformaciones aplicadas:
  STRUCTURE → structure
  STRUCTURE_ID → structure_id
  STRUCTURE_NAME → structure_name
  Time frequency → time_frequency
  Statistical classification of economic activities in the European Community (NACE Rev. 2) → statistical_classification_of_economic_activities_in_the_european_community_nace_rev_2
  Unit of measure → unit_of_measure
  Geopolitical entity (reporting) → geopolitical_entity_reporting
  TIME_PERIOD → time_period
  Time → time
  OBS_VALUE → obs_value
  Observation value → observation_value
  OBS_FLAG → obs_flag
  Observation status (Flag) V2 structure → observation_status_flag_v2_structure
  CONF_STATUS → conf_status
  Confidentiality status (flag) → confidentiality_status_flag

================ DATASET 9 ================
Normalización de nombres de columnas completada.
Columnas procesadas: 19
Transformaciones aplicadas:
  STRUCTURE → structure
  STRUCTURE_ID → structure_id
  STRUCTURE_NAME → structure_name
  Time frequency → time_frequency
  Unit of measure → unit_of_measure
  Sex → sex_1
  Geopolitical entity (reporting) → geopolitical_entity_reporting
  TIME_PERIOD → time_period
  Time → time
  OBS_VALUE → obs_value
  Observation value → observation_value
  OBS_FLAG → obs_flag
  Observation status (Flag) V2 structure → observation_status_flag_v2_structure
  CONF_STATUS → conf_status
  Confidentiality status (flag) → confidentiality_status_flag

================ DATASET 10 ================
Normalización de nombres de columnas completada.
Columnas procesadas: 9
Transformaciones aplicadas:
  DATAFLOW → dataflow
  LAST UPDATE → last_update
  TIME_PERIOD → time_period
  OBS_VALUE → obs_value
  OBS_FLAG → obs_flag
  CONF_STATUS → conf_status

================ DATASET 11 ================
Normalización de nombres de columnas completada.
Columnas procesadas: 23
Transformaciones aplicadas:
  STRUCTURE → structure
  STRUCTURE_ID → structure_id
  STRUCTURE_NAME → structure_name
  Time frequency → time_frequency
  Size classes in number of persons employed → size_classes_in_number_of_persons_employed
  Statistical classification of economic activities in the European Community (NACE Rev. 2) → statistical_classification_of_economic_activities_in_the_european_community_nace_rev_2
  Information society indicator → information_society_indicator
  Unit of measure → unit_of_measure
  Geopolitical entity (reporting) → geopolitical_entity_reporting
  TIME_PERIOD → time_period
  Time → time
  OBS_VALUE → obs_value
  Observation value → observation_value
  OBS_FLAG → obs_flag
  Observation status (Flag) V2 structure → observation_status_flag_v2_structure
  CONF_STATUS → conf_status
  Confidentiality status (flag) → confidentiality_status_flag

#### **3. LIMPIEZA DE VARIABLES CATEGÓRICAS**

- En esta sección se estandariza el formato de las variables categóricas.
- Se eliminan espacios al inicio y al final de los valores y se aplica un formato homogéneo de capitalización.
- Este proceso garantiza la consistencia de las categorías y evita la duplicación de valores equivalentes con distinta representación.

In [45]:
def limpiar_categoricas(df, columnas=None):
    """
    Limpia variables categóricas eliminando espacios y unificando el formato del texto.

    Aplica .str.strip().str.capitalize() para garantizar consistencia en las categorías.

    Parámetros
    ----------
    df : pandas.DataFrame
        DataFrame a procesar.

    columnas : list, default=None
        Columnas a limpiar. Si es None, se aplicará a todas las columnas categóricas.

    Devuelve
    --------
    pandas.DataFrame
        DataFrame con las variables categóricas limpias.
    """

    # Si no se especifican columnas, detectar todas las categóricas
    if columnas is None:
        columnas = df.select_dtypes(include="O").columns

    # Aplicar limpieza básica
    for col in columnas:
        df[col] = df[col].str.strip().str.capitalize()

    return df

In [46]:
for df in dfs:
    limpiar_categoricas(df)

In [47]:
def eliminar_columnas_vacias(df, mostrar_resumen=True):
    """
    Elimina columnas que contienen únicamente valores nulos.

    Parámetros
    ----------
    df : pandas.DataFrame
        DataFrame a procesar.

    mostrar_resumen : bool, default=True
        Si True, muestra qué columnas se han eliminado.

    Returns
    -------
    pandas.DataFrame
        DataFrame sin columnas completamente nulas.
    """

    columnas_vacias = df.columns[df.isnull().all()]
    proteger = ["observation_value"]
    columnas_vacias = [c for c in columnas_vacias if c not in proteger]

    if mostrar_resumen and len(columnas_vacias) > 0:
        print(f"Columnas eliminadas ({len(columnas_vacias)}):")
        for col in columnas_vacias:
            print(f"  - {col}")

    df = df.drop(columns=columnas_vacias)

    return df

In [48]:
for i, df in enumerate(dfs):
    print(f"\n===== DF{i+1} =====")
    dfs[i] = eliminar_columnas_vacias(df)

===== DF1 =====

===== DF2 =====
Columnas eliminadas (5):
  - time
  - obs_flag
  - observation_status_flag_v2_structure
  - conf_status
  - confidentiality_status_flag

===== DF3 =====
Columnas eliminadas (3):
  - time
  - conf_status
  - confidentiality_status_flag

===== DF4 =====

===== DF5 =====
Columnas eliminadas (5):
  - time
  - obs_flag
  - observation_status_flag_v2_structure
  - conf_status
  - confidentiality_status_flag

===== DF6 =====
Columnas eliminadas (3):
  - time
  - conf_status
  - confidentiality_status_flag

===== DF7 =====
Columnas eliminadas (3):
  - time
  - conf_status
  - confidentiality_status_flag

===== DF8 =====
Columnas eliminadas (3):
  - time
  - conf_status
  - confidentiality_status_flag

===== DF9 =====
Columnas eliminadas (3):
  - time
  - conf_status
  - confidentiality_status_flag

===== DF10 =====
Columnas eliminadas (1):
  - conf_status

===== DF11 =====
Columnas eliminadas (1):
  - time

#### **4. TRATAMIENTO DE VALORES NULOS**

- En esta sección se gestionan los valores nulos identificados durante el EDA con el objetivo de garantizar la consistencia y calidad del dataset.  
- Se eliminan los registros que presentan valores nulos en variables categóricas o numéricas, incluyendo las reviews, ya que su ausencia impide su uso en el análisis de sentimiento y en el análisis estructural.  
- Este enfoque es apropiado dado el elevado volumen de datos, permitiendo depurar el dataset sin comprometer su representatividad.  
- Como resultado, se obtiene un dataset íntegro, preparado para las fases posteriores de análisis de sentimiento.

In [49]:
def tratamiento_nulos(df, mostrar_resumen = True):
    """
    Gestiona valores nulos eliminando filas con registros incompletos en variables
    categóricas y numéricas.

    Procedimiento:
    1) Identifica columnas categóricas (object/category) con nulos y elimina filas con nulos en ellas.
    2) Identifica columnas numéricas con nulos y elimina filas con nulos en ellas.
    3) Devuelve el DataFrame resultante (para actualizarlo por asignación).

    Parámetros
    ----------
    df : pandas.DataFrame
        DataFrame de entrada.
    mostrar_resumen : bool, default=True
        Si True, imprime métricas del impacto del filtrado.

    Returns
    -------
    pandas.DataFrame
        DataFrame filtrado tras eliminar filas con nulos en columnas categóricas y numéricas.

    Nota
    ----
    Para “actualizar el dataframe”, reasigna:
    >>> df = tratamiento_nulos(df)
    """

    filas_iniciales = df.shape[0]

    # ---------- CATEGÓRICAS ----------
    cols_cat = df.select_dtypes(include=["object", "category"]).columns.tolist()
    cols_cat_nulos = [c for c in cols_cat if df[c].isna().any()]

    if cols_cat_nulos:
        filas_antes = df.shape[0]
        df = df.dropna(subset=cols_cat_nulos)
        filas_eliminadas_cat = filas_antes - df.shape[0]
    else:
        filas_eliminadas_cat = 0

    # ---------- NUMÉRICAS ----------
    cols_num = df.select_dtypes(include=["number"]).columns.tolist()
    cols_num_nulos = [c for c in cols_num if df[c].isna().any()]

    if cols_num_nulos:
        filas_antes = df.shape[0]
        df = df.dropna(subset=cols_num_nulos)
        filas_eliminadas_num = filas_antes - df.shape[0]
    else:
        filas_eliminadas_num = 0

    # ---------- RESUMEN ----------
    if mostrar_resumen:
        filas_finales = df.shape[0]
        print("Tratamiento de nulos completado")
        print(f"Filas iniciales: {filas_iniciales}")
        print(f"Filas eliminadas (categóricas): {filas_eliminadas_cat}")
        print(f"Filas eliminadas (numéricas): {filas_eliminadas_num}")
        print(f"Filas finales: {filas_finales}")
        print(f"Nulos restantes en el dataset: {df.isna().sum().sum()}")

        if cols_cat_nulos:
            print(f"Columnas categóricas con nulos consideradas: {cols_cat_nulos}")
        if cols_num_nulos:
            print(f"Columnas numéricas con nulos consideradas: {cols_num_nulos}")

    return df

In [50]:
df2 = tratamiento_nulos(df2)

Tratamiento de nulos completado
Filas iniciales: 4533
Filas eliminadas (categóricas): 0
Filas eliminadas (numéricas): 4533
Filas finales: 0
Nulos restantes en el dataset: 0
Columnas numéricas con nulos consideradas: ['time', 'observation_value', 'obs_flag', 'observation_status_flag_v2_structure', 'conf_status', 'confidentiality_status_flag']

#### **5. FILTRADO DE CALIDAD TEXTUAL EN REVIEWS**

- En esta sección se filtran las reviews para garantizar un nivel mínimo de calidad semántica antes del análisis de sentimiento.  
- Se eliminan aquellas entradas con contenido textual insuficiente, definido por un número mínimo de caracteres y palabras, ya que no aportan información relevante y pueden introducir ruido en el análisis.  
- Este proceso permite depurar el corpus textual, mejorando la fiabilidad de los resultados y la robustez de los análisis NLP posteriores.  
- Como resultado, se obtiene un conjunto de reviews informativas y adecuadas para el análisis de sentimiento y la evaluación de la experiencia del usuario.

In [51]:
def filtrar_reviews_por_calidad_textual(
    df,
    col_texto = "review",
    min_chars = 30,
    min_words = 5,
    mostrar_resumen = True
):
    """
    Filtra reviews con contenido textual insuficiente para garantizar calidad semántica
    en análisis de sentimiento y procesos NLP posteriores.

    Este procedimiento elimina registros cuyo contenido no cumple umbrales mínimos
    de longitud en caracteres y número de palabras, reduciendo ruido y mejorando
    la robustez analítica.

    Parámetros
    ----------
    df : pd.DataFrame
        DataFrame de entrada que contiene la columna de reviews.

    col_texto : str, default="Review"
        Nombre de la columna que contiene el texto de las reviews.

    min_chars : int, default=30
        Número mínimo de caracteres requeridos para conservar una review.

    min_words : int, default=5
        Número mínimo de palabras requeridas para conservar una review.

    mostrar_resumen : bool, default=True
        Si True, muestra métricas de impacto del filtrado.

    Returns
    -------
    pd.DataFrame
        Nuevo DataFrame filtrado con únicamente reviews válidas.

    Notas
    -----
    Este filtrado mejora la calidad del corpus textual eliminando entradas no
    informativas como respuestas triviales o incompletas.

    Ejemplo
    -------
    >>> df_filtrado = filtrar_reviews_por_calidad_textual(df, "Review", 30, 5)
    """

    # Validación de existencia de la columna
    if col_texto not in df.columns:
        raise ValueError(f"La columna '{col_texto}' no existe en el DataFrame")

    # Registro de métricas iniciales
    filas_antes = df.shape[0]

    # Normalización del texto
    texto_normalizado = (
        df[col_texto]
        .astype("string")
        .str.replace(r"\s+", " ", regex=True)
        .str.strip()
    )

    # Cálculo de métricas de calidad textual
    char_len = texto_normalizado.fillna("").str.len()
    word_count = texto_normalizado.fillna("").str.findall(r"\b\w+\b").str.len()

    # Construcción de máscara de filtrado
    mask_reviews_validas = (
        (char_len >= min_chars) &
        (word_count >= min_words)
    )

    # Aplicación del filtrado
    df_filtrado = df.loc[mask_reviews_validas].copy()

    # Métricas finales
    filas_despues = df_filtrado.shape[0]
    filas_eliminadas = filas_antes - filas_despues
    nulos_restantes = df_filtrado[col_texto].isna().sum()

    # Reporte de resultados
    if mostrar_resumen:
        print("Filtrado de calidad textual completado")
        print(f"Filas iniciales: {filas_antes}")
        print(f"Filas retenidas: {filas_despues}")
        print(f"Filas eliminadas por contenido insuficiente: {filas_eliminadas}")
        print(f"Nulos restantes en '{col_texto}': {nulos_restantes}")

    return df_filtrado

In [52]:
df2 = filtrar_reviews_por_calidad_textual(
    df2,
    col_texto="review",
    min_chars=30,
    min_words=5
)

ValueError: La columna 'review' no existe en el DataFrame

#### **6. PROCESAMIENTO DE VARIABLES TEMPORALES**

- En esta sección se convierte la variable temporal `date_time` al tipo datetime para garantizar su correcto tratamiento analítico.
- Esta transformación permite interpretar la variable como una dimensión temporal real, en lugar de texto, asegurando coherencia en ordenaciones y agregaciones.
- A partir de esta variable, se generan nuevas features temporales (`year`, `month`, `day`, `weekday`, `hour`) que facilitan el análisis de patrones de uso y evolución temporal de las reviews.
- Este procesamiento permite analizar tendencias, estacionalidad y comportamiento de los usuarios a lo largo del tiempo, mejorando la capacidad analítica del dataset.

In [ ]:
def procesar_variable_temporal(
    df,
    col_fecha = "datetime",
    eliminar_original = False,
    mostrar_resumen = True
):
    """
    Convierte una columna a tipo datetime y genera variables temporales derivadas
    para facilitar el análisis temporal.

    Variables creadas:
    - year: año
    - month: mes (numérico)
    - month_name: nombre del mes
    - day: día del mes
    - weekday: nombre del día de la semana
    - hour: hora del día
    - date: fecha (sin hora)

    Parámetros
    ----------
    df : pandas.DataFrame
        DataFrame de entrada.

    col_fecha : str, default="datetime"
        Nombre de la columna temporal a procesar.

    eliminar_original : bool, default=False
        Si True, elimina la columna original tras crear las variables derivadas.

    mostrar_resumen : bool, default=True
        Si True, muestra un resumen del proceso.

    Returns
    -------
    pandas.DataFrame
        DataFrame con la variable temporal convertida y nuevas features creadas.

    Ejemplo
    -------
    >>> df = procesar_variable_temporal(df, "date_time")
    """

    df = df.copy()

    # Validación
    if col_fecha not in df.columns:
        raise ValueError(f"La columna '{col_fecha}' no existe en el DataFrame")

    # Conversión a datetime
    df[col_fecha] = pd.to_datetime(df[col_fecha], errors="coerce")

    # Métricas
    nulos_generados = df[col_fecha].isna().sum()

    # Creación de variables derivadas
    df["year"] = df[col_fecha].dt.year
    df["month"] = df[col_fecha].dt.month
    df["month_name"] = df[col_fecha].dt.month_name()
    df["day"] = df[col_fecha].dt.day
    df["weekday"] = df[col_fecha].dt.day_name()
    df["hour"] = df[col_fecha].dt.hour
    df["date"] = df[col_fecha].dt.date

    # Eliminar original si se solicita
    if eliminar_original:
        df.drop(columns=[col_fecha], inplace=True)

    # Resumen
    if mostrar_resumen:
        print("Procesamiento de variable temporal completado")
        print(f"Columna procesada: {col_fecha}")
        print(f"Nulos generados tras conversión: {nulos_generados}")
        print("Variables creadas: year, month, month_name, day, weekday, hour, date")

    return df

In [ ]:
df2 = procesar_variable_temporal(df2, col_fecha="date_time")

#### **7. REDUCCIÓN DEL DATASET MEDIANTE MUESTREO ESTRATIFICADO**

- Dado el elevado volumen del dataset original, se aplica un muestreo estratificado para reducir su tamaño a una muestra manejable sin comprometer su representatividad.
- El muestreo se realiza preservando la distribución conjunta de las variables `Rating` y `App`, consideradas dimensiones clave al estar directamente relacionadas con el sentimiento y el contexto de la review.
- Este enfoque garantiza que la muestra mantenga la misma estructura proporcional que el dataset original, evitando sesgos derivados de un muestreo aleatorio simple que podría infra o sobre-representar determinados perfiles.
- La muestra resultante permite reducir significativamente el coste computacional del análisis de sentimiento, manteniendo al mismo tiempo la validez analítica y la capacidad de generalización de los resultados.
- Este procedimiento optimiza el equilibrio entre eficiencia computacional y robustez estadística, facilitando el análisis sobre grandes volúmenes de datos en entornos con recursos limitados.

In [ ]:
def muestreo_estratificado(df, n=50_000, cols_estrato=["rating", "app"], random_state=42):
    """
    Genera una muestra estratificada proporcional a partir de un DataFrame,
    preservando la distribución de las variables especificadas.

    Este procedimiento reduce el tamaño del dataset sin introducir sesgos
    relevantes, manteniendo la representatividad de variables clave como
    Rating y App.

    Parámetros
    ----------
    df : pd.DataFrame
        DataFrame original.

    n : int, default=50_000
        Número de filas deseadas en la muestra.

    cols_estrato : list of str, default=["Rating", "App"]
        Columnas utilizadas para definir los estratos.

    random_state : int, default=42
        Semilla para reproducibilidad.

    Returns
    -------
    df_sample : pd.DataFrame
        DataFrame muestreado de forma estratificada.
    """

    df_temp = df.copy()
    df_temp.columns = df_temp.columns.str.strip()

    # resolver nombres reales de columnas (case-insensitive)
    col_map = {c.lower(): c for c in df_temp.columns}
    cols_resueltas = [col_map[c.lower()] for c in cols_estrato]

    # crear estrato
    df_temp["_stratum"] = df_temp[cols_resueltas].astype(str).agg("|".join, axis=1)

    # muestreo proporcional
    df_sample = (
        df_temp.groupby("_stratum", group_keys=False)
        .apply(lambda x: x.sample(
            n=max(1, round(n * len(x) / len(df_temp))),
            random_state=random_state
        ))
        .reset_index(drop=True)
    )

    # ajustar EXACTAMENTE a n filas
    if len(df_sample) > n:
        df_sample = df_sample.sample(n=n, random_state=random_state)
    elif len(df_sample) < n:
        faltan = n - len(df_sample)
        extra = df_temp.drop(df_sample.index).sample(n=faltan, random_state=random_state)
        df_sample = pd.concat([df_sample, extra], ignore_index=True)

    return df_sample.drop(columns="_stratum")

In [ ]:
df2 = muestreo_estratificado(df2, n=50_000)

print(df2.shape)

#### **8. EXPORTACIÓN DEL DATASET LIMPIO**

- En esta sección se exportan los datasets tras aplicar los procesos de limpieza, tratamiento de nulos y transformación de variables.
- Los datasets se guardan en formato `.csv` dentro del directorio `data/processed/`, siguiendo una estructura organizada del proyecto.
- Esta exportación garantiza la reutilización de los mismos sin necesidad de repetir las fases de preparación.

In [ ]:
output_path_reviews = "../data/processed/dating_app_reviews_clean.csv"

df2.to_csv(output_path_reviews, index=False)

print("Exportación completada correctamente:")
print(f"  - Reviews:        {output_path_reviews}")